### ISSUE TITLE
Error at nativescript-dev-webpack installation 

### ISSUE THREAD

**Issue by roshan3133** [NativeScript/nativescript-angular#1006]
I am getting below error my app root dir is /angular_basic_app and package.json is in this dir and my actual app code is in src/app dir
```
$ npm install --save-dev nativescript-dev-webpack

> nativescript-dev-webpack@0.8.0 postinstall /angular_basic_app/node_modules/nativescript-dev-webpack
> node postinstall.js

Creating file: /angular_basic_app/app/vendor-platform.android.ts
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/angular_basic_app/app/vendor-platform.android.ts'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at copyTemplate (/angular_basic_app/node_modules/nativescript-dev-webpack/projectFilesManager.js:74:12)
    at /angular_basic_app/node_modules/nativescript-dev-webpack/projectFilesManager.js:44:9
    at Array.forEach (native)
    at Object.addProjectFiles (/angular_basic_app/node_modules/nativescript-dev-webpack/projectFilesManager.js:42:31)
    at Object.install (/angular_basic_app/node_modules/nativescript-dev-webpack/installer.js:15:25)
    at Object.<anonymous> (/angular_basic_app/node_modules/nativescript-dev-webpack/postinstall.js:2:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-dev-webpack@0.8.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-dev-webpack@0.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2017-09-25T13_30_46_557Z-debug.log
```

**Comment by roshan3133** [comment]
Opened in wrong rpeo, so closing issue here and same opened in  https://github.com/NativeScript/nativescript-dev-webpack/issues/276
