### ISSUE TITLE
Occasional crash in NSRouteReuseStrategy.shouldAttach()

### ISSUE THREAD

**Issue by gsmedley** [NativeScript/nativescript-angular#1048]
Sometimes after debugging for a while, I get a crash when going back from a page. The error says  key is  not defined in `NSRouteReuseStrategy.shouldAttach()` here:

` const shouldAttach = isBack && this.cache.peek().key === key;`

I see in other places nearby there is a check that `this.cache.peek()` exists before calling .key.

**Comment by corne-de-bruin** [comment]
After upgrading our app from NativeScript 3.1 to 3.2 (or 3.3) we are facing the same issue when we use the back button on android afer the user opened a deep link.

```
TypeError: Cannot read property 'key' of undefined
     at NSRouteReuseStrategy.shouldAttach (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/nativescript-angular/router/ns-route-reuse-strategy.js:64:55)
     at ActivateRoutes.activateRoutes (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/@angular/router/bundles/router.umd.js:4743:45)
     at file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/@angular/router/bundles/router.umd.js:4715:58
     at Array.forEach (native)
     at ActivateRoutes.activateChildRoutes (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/@angular/router/bundles/router.umd.js:4715:29)
     at ActivateRoutes.activateRoutes (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/@angular/router/bundles/router.umd.js:4736:22)
     at file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/@angular/router/bundles/router.umd.js:4715:58
     at Array.forEach (native)
     at ActivateRoutes.activateChildRoutes (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/@angular/router/bundles/router.umd.js:4715:29)
     at ActivateRoutes.activate (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/@angular/router/bundles/router.umd.js:4608:14)
     at file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/@angular/router/bundles/router.umd.js:4185:22
     at SafeSubscriber._next (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/rxjs/Observable.js:224:21)
     at SafeSubscriber.__tryOrSetError (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/rxjs/Subscriber.js:247:16)
     at SafeSubscriber.next (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/rxjs/Subscriber.js:187:27)
     at Subscriber._next (file:///data/data/nl.energiedirect.selfserviceapp/files/app/tns_modules/rxjs/Subscriber.js:125:26)

```

**Comment by dennis-montana** [comment]
This is also happening in our app with NativeScript 3.2 and 3.3 on iOS. When routing to a page using a deep link and then clicking the back button:
```ts
Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this.cache.peek().key')

shouldAttach@file:///app/tns_modules/nativescript-angular/router/ns-route-reuse-strategy.js:64:55  
activateRoutes@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4743:57  
file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4715:72  
forEach@[native code]  
```

**Comment by corne-de-bruin** [comment]
After more debugging I've found that this will happen on a back route after a clear history.
So after a certain action we call a route with a clear history, that route calls another one directly. If we then click the back button to go to the first route we will get this error.

**Comment by gsmedley** [comment]
So - is anyone paying attention to crashing bugs that have simple, risk-free fixes?

**Comment by gogoout** [comment]
This also happens to my app. When user logined, we will redirect the user to home page with a clearHistory  flag. If the user then hitting whatever redirection buttons on the home page as fast as they can, they will run into  this issue when they try go back.

The issue is raised by the usage of setTimeout. Any particular reason to use setTimeout?

```log
JS: clearHistory,run setTimeout
JS: navigatingFromEvent
JS: actually clear cache
```

**Comment by corne-de-bruin** [comment]
With NS 5.3.1 and NS-Angular 7.2.3 we are seeing similar behaviour again on back routing after a clearHistory. But instead of the app crashing we end up with a blank page.

I've created a sample application that shows the same behaviour.
https://play.nativescript.org/?template=play-ng&id=m84Itu

If you open this app it will navigate from the home to a second page (with a pink background) and then to a third page with a blue background. If you then navigate back the second page (pink one) is empty (blank).

In our production app I could fix this behaviour by changing the loadComponentInPage  function of the PageRouterOutlet.
```
// Component loaded. Find its root native view.
    const componentView = componentRef.location.nativeElement;
    // Remove it from original native parent.
    this.viewUtil.removeChild(componentView.parent, componentView);
    // Add it to the new page
    page.content = componentView;

    page.on(Page.navigatedFromEvent, (<any>global).Zone.current.wrap((args: NavigatedData) => {
        if (args.isBackNavigation) {
            this.locationStrategy._beginBackPageNavigation(this.frame);
            this.locationStrategy.back(null, this.frame);
        }
    }));

    const navOptions = this.locationStrategy._beginPageNavigation(this.frame);

    // Clear refCache if navigation with clearHistory
    if (navOptions.clearHistory) {
        const clearCallback = () => () => {
            if (this.outlet) {
                this.routeReuseStrategy.clearCache(this.outlet.outletKeys[0]);
            }
            page.off(Page.navigatedToEvent, clearCallback);
        };

        page.on(Page.navigatedToEvent, clearCallback);
    }

    this.frame.navigate({
        create: () => { return page; },
        clearHistory: navOptions.clearHistory,
        animated: navOptions.animated,
        transition: navOptions.transition
    });
```

I just removed the setTimeout call around the callback function.

**Comment by bachras** [comment]
I am having same issue as well

**Comment by joshcomley** [comment]
I had this issue if I called `frameModule.topmost().goBack()` one too many times

**Comment by NeriCodec** [comment]
`import { RouterExtensions } from "nativescript-angular/router";
`
I had this issue if I called routerExtensions.back() too many...

**Comment by NazimMertBilgi** [comment]
is there any improvement on this subject?

**Comment by NazimMertBilgi** [comment]
Workaround:

    application.android.on(AndroidApplication.activityBackPressedEvent, (data: AndroidActivityBackPressedEventData) => {
      const validate = this.router.url === "/home/default/(usersListTab:users-list//messagesTab:messages//notificationsTab:notifications//myProfileTab:my-profile)";
      if (validate) {
        data.cancel = true; // prevents default back button behavior
      }
    });
