### ISSUE TITLE
Unhandled Promise rejection: undefined is not an object (evaluating 'this._selectors.query'): Project crashes since last reinit of node_modules folder, pointing to nativescript-angular

### ISSUE THREAD

**Issue by noomieware** [NativeScript/nativescript-angular#1065]
Hi, I had to resetup my node_modules after an crash. Since then, I keep getting the error below.

It seems not to be related to my code, as older versions from my git also dont work anymore. Complete reinstallation of node, npm, nativescript and all packages did not help. 

Maybe this is related to a newer version of a package used, but stacktrace is pointing to nativescript-angular first hand (see last line).

I'm not sure, what exactly raises such error from stack trace. But as said, The same state of my code worked before.

```
2017-10-31 13:43:57.759438+0100  localhost charenjinative[9521]: (NativeScript) CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:569:26: Unhandled Promise rejection: undefined is not an object (evaluating 'this._selectors.query') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: undefined is not an object (evaluating 'this._selectors.query') matchSelectors@file:///app/tns_modules/tns-core-modules/ui/styling/style-scope.js:491:31
updateMatch@file:///app/tns_modules/tns-core-modules/ui/styling/style-scope.js:258:83
onLoaded@file:///app/tns_modules/tns-core-modules/ui/styling/style-scope.js:249:29
onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:183:32
onLoaded@file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:93:39
2017-10-31 13:43:57.759579+0100  localhost charenjinative[9521]: (NativeScript) CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:571:22: Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this._selectors.query')
matchSelectors@file:///app/tns_modules/tns-core-modules/ui/styling/style-scope.js:491:31
updateMatch@file:///app/tns_modules/tns-core-modules/ui/styling/style-scope.js:258:83
onLoaded@file:///app/tns_modules/tns-core-modules/ui/styling/style-scope.js:249:29
onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:183:32
onLoaded@file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:93:39
_addViewCore@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:344:26
_addViewCore@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:23:43
_addView@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:330:26
set@file:///app/tns_modules/tns-core-modules/ui/content-view/content-view.js:23:30
file:///app/tns_modules/nativescript-angular/
```
Thx for any hints

**Comment by tsonevn** [comment]
Hi @noomieware ,
Thank you for your interest in NativeScript.
Could you provide more info about the case and your environment(CLI, node, npm, tns-core-modules, nativescript-angular versions)? It would help if you could send us the project, which would help to investigate further the problem.

Also, you could build the project with `tns run <platform name >--log trace` and to send us the full log from the console.

**Comment by noomieware** [comment]
Hi @tsonevn,

I have to thank you for taking the time to investigate on my issue. 

Due to company policy, I'm not allowed to fully share the project. But I will share as much information as I can to help you helping me ;).

I'm working on MacOS, with following versions:

node v6.11.5 (installed by brew node@6)
npm 5.4.2 (was downgrading to 5.3.0 once, didnt help)
tns cli version 3.3.0 (had 3.2.0 before, same issue)

also pls see my attached package.json, tsconfig and the log.trace


[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1435769/Archive.zip)

Thx in advance

**Comment by noomieware** [comment]
I was able to test on an android device meanwhile. While an error is logged, application works here.

The error I got:
`
System.err: com.tns.NativeScriptException:
System.err: Calling js method onStart failed
System.err: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
System.err:     org.nativescript.widgets.ViewHelper.setMarginTop(ViewHelper.java:194)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:38)
System.err:     android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
System.err:     android.app.Activity.performStart(Activity.java:6295)
System.err:     android.app.Activity.performRestart(Activity.java:6341)
System.err:     android.app.ActivityThread.handleSleeping(ActivityThread.java:3738)
System.err:     android.app.ActivityThread.access$2900(ActivityThread.java:163)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:148)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5585)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
System.err: File: "file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js, line: 537, column: 16
System.err: StackTrace:
System.err:     Frame: function:'View.(anonymous function)', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 537, column: 17
System.err:     Frame: function:'applyAllNativeSetters', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 972, column: 37
System.err:     Frame: function:'initNativeView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 899, column: 9
System.err:     Frame: function:'ViewBase.onResumeNativeUpdates', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 539, column: 22
System.err:     Frame: function:'ViewBase._resumeNativeUpdates', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 207, column: 18
System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 184, column: 14
System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err:     Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err:     Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err:     Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err:     Frame: function:'Page.onLoaded', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 105, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err:     Frame: function:'FrameBase.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 385, column: 13
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err:     Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err:     Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 640, column: 22
System.err:     Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 26, column: 25
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:38)
System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
System.err:     at android.app.Activity.performStart(Activity.java:6295)
System.err:     at android.app.Activity.performRestart(Activity.java:6341)
System.err:     at android.app.ActivityThread.handleSleeping(ActivityThread.java:3738)
System.err:     at android.app.ActivityThread.access$2900(ActivityThread.java:163)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5585)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
System.err:     at org.nativescript.widgets.ViewHelper.setMarginTop(ViewHelper.java:194)
System.err:     ... 19 more
ActivityManager: cleanUpApplicationRecord -- 30017
ActivityManager: Spurious death for ProcessRecord{c6306db 30427:org.nativescript.charenjiapp/u0a111}, curProc for 30017: null
`

maybe an additional hint.

**Comment by tsonevn** [comment]
Hi @noomieware,
Thank you for the provided info,
We are still unable to recreate the issue on our side and we are researching, what could cause this error.
We will write you back as soon as we have some further info on the case.

It would help if you could isolate the problem in a sample project.

**Comment by noomieware** [comment]
Hi @tsonevn,

thx for coming back to my issue. I'll try to isolate on a sample project. This might take a while, as a new project from hello world angular template works.

Meanwhile, I can clearly state, that this is just on IOS. Project works for me on an Android device. The earlier mentioned stacktrace from android was caused by something else.

**Comment by chrisbellman** [comment]
Not sure if this is helpful. I'm also getting `CONSOLE WARN file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:14:46: Class "UITextViewDelegateImpl" already implements the "UIScrollViewDelegate" protocol.` in my console. iOS still works, I just get the error. Am not sure what is causing it but will report back if I make any discoveries.

**Comment by tsonevn** [comment]
Hi @chrisbellman,
Thank you for contacting us.
Could you provide sample project, which could be debugged locally on our side? This will help to investigate this issue further.

**Comment by NathanWalker** [comment]
@tsonevn curiously I was updating Rowdy's EU dev day app to {N} 3.4 and Angular 5 and have run into this very same thing. Very strange. If you clone and run this should see it:
https://github.com/NathanWalker/NSDevDayEU

I get exactly what @chrisbellman is getting - tried many things - very puzzling.

**Comment by noomieware** [comment]
Coming back to that issue and my mac after a while, I updated my app to 3.4. and can share the experience of @NathanWalker and @chrisbellman:

CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1052:24: ERROR TypeError: undefined is not an object (evaluating 'this._selectors.query')
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:165:30: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:165:30: ns-renderer: undefined is not an object (evaluating 'this._selectors.query')
CONSOLE WARN file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:14:46: Class "UITextViewDelegateImpl" already implements the "UIScrollViewDelegate" protocol.
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:569:26: Unhandled Promise rejection: undefined is not an object (evaluating 'this._selectors.query') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: undefined is not an object (evaluating 'this._selectors.query') matchSelectors@file:///app/tns_modules/tns-core-modules/ui/styling/style-scope.js:505:31
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:571:22: Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this._selectors.query')

So it seems, we eventually have a sharable project to fiddle with that error https://github.com/NathanWalker/NSDevDayEU 
Thanks @NathanWalker

**Comment by noomieware** [comment]
For testing purposes, I brutally changed the mentioned tns-core-modules/ui/styling/style-scope.js to always createSelectors:

```
    StyleScope.prototype.ensureSelectors = function () {
        //if (this._applicationCssSelectorsAppliedVersion !== applicationCssSelectorVersion ||
          //  this._localCssSelectorVersion !== this._localCssSelectorsAppliedVersion ||
            //!this._mergedCssSelectors) {
            this._createSelectors();
        //}
        return this._getSelectorsVersion();
    };
```

Running with this version on ios, the app starts without errors. Seems like the condition is not met to initially create the selectors. Why? Donno. But maybe this hints someone knowing more about the core modules thing.

**Comment by tsonevn** [comment]
Hi @NathanWalker,
Thank you for the sample project, where the issue could be recreated.
@noomieware thanks for the suggestion. We will investigate further this case and will verify, what could cause this case.
Regarding that, any [PR, which provides a fix ](https://www.nativescript.org/contribute) for this bug will be highly appreciated

**Comment by NathanWalker** [comment]
@tsonevn some extra insight here -- I was working on another project and ran into this after I attempted to use `APP_INITIALIZER` in the root AppModule. Could be something that interferes with this or causes this when extra app initializer functions are added. The error again that results when setting up a custom initializer as follows:

```
export function appInitFactory(appService) {
  return () => {
    // for now, this is here to construct AppService on boot
    // in future, may want to call init routines here inside the service
  };
}

@NgModule({
  imports: [
    CoreModule,
    SharedModule,
    AppRoutingModule
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: appInitFactory,
      deps: [AppService],
      multi: true
    }
  ]
})
export class AppModule {}
```

results in this crash on startup:
```
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:165:30: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:165:30: ns-renderer: Provider parse errors:
CONSOLE WARN file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:14:46: Class "UITextViewDelegateImpl" already implements the "UIScrollViewDelegate" protocol.
```

If I remove the custom `APP_INITIALIZER` the error simply goes away and the app launches as normal. Very puzzling but may provide a clue?

/cc @sis0k0 @vakrilov

**Comment by vakrilov** [comment]
Thanks for the info @NathanWalker. Sure looks like a strange bug.
Can you share if there is something more interesting in the `AppService` code.

One thing that comes to my mind is that all code before the bootstrap in IOS is executed before the main application loo[ is started. Some implications - the timer functions (`setTimeout`/`setInterval`) might not work as expected as they rely on the app-loop. This crash does not seem like that, but there might be other things happening that rely on the application loop that are causing the issue.
