### ISSUE TITLE
Back navigation crash

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-angular#1072]
When the back button in Action Bar is tapped several times quickly, the app crashes. The same doesn't happen when using the hardware button.

Error log:
```
System.err: com.tns.NativeScriptException: 
System.err: Calling js method run failed
System.err: TypeError: Cannot read property 'resolvedPage' of undefined
System.err: File: "file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 142, column: 24
System.err: StackTrace: 
System.err: 	Frame: function:'FrameBase._onNavigatingTo', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 306, column: 23
System.err: 	Frame: function:'FrameBase.performGoBack', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 289, column: 14
System.err: 	Frame: function:'FrameBase._processNavigationContext', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 258, column: 18
System.err: 	Frame: function:'Frame._processNavigationContext', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 259, column: 52
System.err: 	Frame: function:'FrameBase._processNavigationQueue', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 225, column: 18
System.err: 	Frame: function:'Frame.setCurrent', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 83, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 523, column: 53
System.err: 	Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 398, column: 31
System.err: 	Frame: function:'Zone.runTask', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 165, column: 47
System.err: 	Frame: function:'ZoneTask.invoke', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 460, column: 38
System.err: 	Frame: function:'timer', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1634, column: 29
System.err: 	Frame: function:'invoke', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err: 	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 365, column: 26
System.err: 	Frame: function:'Zone.runGuarded', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 138, column: 47
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 116, column: 29
System.err: 	Frame: function:'run', file:'file:///data/data/org.nativescript.nativescriptsdkexamplesng/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:168)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5781)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
ActivityManager: Recipient 20460
ActivityManager: Process org.nativescript.nativescriptsdkexamplesng (pid 20460) has died

```
Reproducible with NativeScript SDK Examples on Android.

**Comment by BasyaLipman** [comment]
@sis0k0 - I'm getting something similar when pressing back nav Hardware button multiple times quickly on Android in my NS + Angular app.

Using TNS 1.3.4 and 
`"@angular/animations": "4.3.2",
    "@angular/common": "4.3.2",
    "@angular/compiler": "4.3.2",
    "@angular/core": "4.3.2",
    "@angular/forms": "4.3.2",
    "@angular/http": "4.3.2",
    "@angular/platform-browser": "4.3.2",
    "@angular/router": "4.3.2",
    "nativescript-angular": "4.2.0",`

And here's the error:

`com.tns.NativeScriptException: Calling js method run failed TypeError: Cannot read property '_callbacks' of null File: "file:///data/data/com.x.y/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 142, column: 24 StackTrace: Frame: function:'getFragmentCallbacks', file:'file:///data/data/com.x.y/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 27, column: 20 Frame: function:'', file:'file:///data/data/com.x.y/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 521, column: 60 Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/com.x.y/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 398, column: 31 Frame: function:'Zone.runTask', file:'file:///data/data/com.x.y/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 165, column: 47 Frame: function:'ZoneTask.invoke', file:'file:///data/data/com.x.y/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 460, column: 38 Frame: function:'timer', file:'file:///data/data/com.x.y/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1634, column: 29 Frame: function:'invoke', file:'file:///data/data/com.x.y/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48 Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/com.x.y/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 365, column: 26 Frame: function:'Zone.runGuarded', file:'file:///data/data/com.x.y/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 138, column: 47 Frame: function:'', file:'file:///data/data/com.x.y/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 116, column: 29 Frame: function:'run', file:'file:///data/data/com.x.y/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13`

**Comment by manijak** [comment]
Using vanilla TNS 4.1.0, Android runtime 4.1.3 and got this error in the "Pre-launch report" on Google play.

```
FATAL EXCEPTION: main
Process: com.myapp, PID: 11615
com.tns.NativeScriptException: 
Calling js method run failed
TypeError: Cannot read property 'resolvedPage' of undefined
File: "file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js, line: 182, column: 42
StackTrace: 
	Frame: function:'FrameBase._processNavigationQueue', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 182, column: 43
	Frame: function:'Frame.setCurrent', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 204, column: 18
	Frame: function:'', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 578, column: 53
	Frame: function:'invoke', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'run', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
	at com.tns.Runtime.callJSMethod(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:954)
	at com.tns.Runtime.callJSMethod(Runtime.java:946)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by tsonevn** [comment]
Hi @manijak,
I tested this scenario with the latest modules 4.1.0 and tns-android 4.1.3, however, was unable to recreate the issue. Can you provide sample project, which can be used for debugging? For your convenience, I am attaching a sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2206093/Archive.zip)

**Comment by manijak** [comment]
Hi @tsonevn,
Not something I was able to reproduce either, but it was reported from Google in the "Pre-launch report" and their tests.

**Comment by vakrilov** [comment]
This issue was fixed in the `tns-core-modules` package.
