### ISSUE TITLE
[Angular 5] Error: ENFILE: file table overflow

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-angular#1079]
### Error:
```
Error: ENFILE: file table overflow
```

### Description:
It looks like the {N} CLI running a NativeScript-Angluar 5 project hits the issue with Node process monitoring too many open files at once related to the new [i18n](https://angular.io/guide/i18n).

### Workaround:
[This](http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit) blog post.

### Steps to reproduce:
```
git clone git@github.com:NativeScript/sample-Groceries.git && cd sample-Groceries
npm install --save nativescript-angular@rc
./node_modules/.bin/update-app-ng-deps
tns run android
```

### Output:
```
Project successfully built.
Installing...
Successfully installed on device with identifier 'emulator-5554'.
Unable to apply changes on device: emulator-5554. Error is: ENFILE: file table overflow, open '/Users/vchimev/Work/git/sample-Groceries/platforms/android/src/main/assets/app/tns_modules/tns-core-modules/ui/layouts/dock-layout/dock-layout-common.js'.
The project file undefined is corrupted.
Consider restoring an earlier version from your source control or backup.
Additional technical info: Error: ENFILE: file table overflow, open '/Users/vchimev/Work/git/sample-Groceries/package.json'
Failed to display command help { Error: ENFILE: file table overflow, open '/usr/local/lib/node_modules/nativescript/lib/common/commands/help.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Yok.resolveDependency (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:338:13)
    at Yok.resolveByName (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:315:31)
  errno: -23,
  code: 'ENFILE',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/nativescript/lib/common/commands/help.js' }
```

Related to https://github.com/NativeScript/nativescript-angular/issues/1073.

**Comment by TomK32** [comment]
I put a simple console.log(name) into /usr/local/lib/node_modules/nativescript/lib/common/yok.js `resolveDependency` and looks like `logger` is requiring itself somewhere causing an endless loop.

**Comment by sis0k0** [comment]
Fixed with https://github.com/NativeScript/nativescript-cli/pull/3277 and https://github.com/telerik/mobile-cli-lib/pull/1036

**Comment by flynsequeira** [comment]
Facing the same issue.
