### ISSUE TITLE
Typescript compiler failed

### ISSUE THREAD

**Issue by narayansikarwar** [NativeScript/nativescript-angular#1105]
Everything was working fine in last day, but today suddenly I am facing following issue
when I run **tns run android** command

And I have also try **tns update/ tns install** after deleting the **node_modules** folder, **tns platform remove/add android** but nothing happened.

Searching for devices...
Executing before-liveSync hook from C:\NativescriptApps\ToDoApp\hooks\before-liveSync\nativescript-angular-sync.js
Executing before-prepare hook from C:\NativescriptApps\ToDoApp\hooks\before-prepare\nativescript-dev-sass.js
Found peer node-sass
Executing before-prepare hook from C:\NativescriptApps\ToDoApp\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
C:\NativescriptApps\ToDoApp\node_modules\typescript\lib\tsc.js:1755
            basePaths: getBasePaths(path
                                    ^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 1.
Executing after-watch hook from C:\NativescriptApps\ToDoApp\hooks\after-watch\nativescript-dev-sass.js
Executing after-watch hook from C:\NativescriptApps\ToDoApp\hooks\after-watch\nativescript-dev-typescript.js

**Comment by tsonevn** [comment]
Hi @narayansikarwar,
Could you send us the project or sample code, which could be used for recreating the issue?
After reviewing the error it seems that the issue is related to a mistake in the project.
It would help also if you could provide more info about your environment(CLI, modules, runtime versions).

Thank you in advance for the cooperation.

**Comment by narayansikarwar** [comment]
Hi @tsonevn,
I have used your angular tab project tns-template-tab-navigation-ng.
All NativeScript components versions information

 Component       Current version
 nativescript            3.3.0        
 tns-core-modules  3.3.0          
 tns-android            3.3.1          
 tns-ios                    3.3.0
Thanks

**Comment by tsonevn** [comment]
Hi @narayansikarwar,
I tested this issue while using the latest version of the template `3.3.3` and the typescript `2.4.2` and the sample project is built as expected. 
Could you check which version of the typescript, you are using via `tsc --version` and if it is different try installing typescript 2.4.2.  Clear node cache with `npm cache clear`. Create new project with `tns create my-app-name --template tns-template-tab-navigation-ng` and try to build it again with `tns run <platform name>`

**Comment by narayansikarwar** [comment]
Hi @tsonevn,
I have typescript version 2.4.2, and I tried your above steps but still same error occurred.
A complete process is given below please check and let me know if I miss something...
C:\TFS Projects>tns --version
3.3.1
C:\TFS Projects>node --version
v8.9.1
C:\TFS Projects>npm --version
5.5.1
C:\TFS Projects>tsc --version
Version 2.4.2
C:\TFS Projects>npm cache clear --force
npm WARN using --force I sure hope you know what you are doing.
C:\TFS Projects>tns create my-app-name --template tns-template-tab-navigation-ng
Installing  tns-template-tab-navigation-ng
preinstall script running...
creating C:\TFS Projects\my-app-name\tslint.json...
postinstall script running...
Updating package.json scripts for linting...
Removing tools directory...
(node:4236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ tns-template-tab-navigation-ng@3.3.3
added 19 packages in 72.531s

> node-sass@4.5.3 install C:\TFS Projects\my-app-name\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\nsingh\AppData\Roaming\npm-cache\node-sass\4.5.3\win32-x64-57_binding.node

> node-sass@4.5.3 postinstall C:\TFS Projects\my-app-name\node_modules\node-sass
> node scripts/build.js

Binary found at C:\TFS Projects\my-app-name\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine

> nativescript-dev-sass@1.3.2 postinstall C:\TFS Projects\my-app-name\node_modules\nativescript-dev-sass
> node postinstall.js


> nativescript-dev-typescript@0.5.1 postinstall C:\TFS Projects\my-app-name\node_modules\nativescript-dev-typescript
> node postinstall.js

Adding 'es6' lib to tsconfig.json...
Adding 'dom' lib to tsconfig.json...
Adding 'es2015.iterable' lib to tsconfig.json...
Adding tns-core-modules path mappings lib to tsconfig.json...
Project already targets TypeScript 2.4.2
added 215 packages in 126.24s
Project my-app-name was successfully created.
C:\TFS Projects>cd my-app-name
C:\TFS Projects\my-app-name>tns run android
Searching for devices...
Executing before-liveSync hook from C:\TFS Projects\my-app-name\hooks\before-liveSync\nativescript-angular-sync.js
Copying template files...
  \ Installing tns-androidInstalling  tns-android
| Installing tns-android[..................]
Project successfully created.
Searching for devices...
Executing before-liveSync hook from C:\TFS Projects\my-app-name\hooks\before-liveSync\nativescript-angular-sync.js
Executing before-prepare hook from C:\TFS Projects\my-app-name\hooks\before-prepare\nativescript-dev-sass.js
Found peer node-sass
Executing before-prepare hook from C:\TFS Projects\my-app-name\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
C:\TFS Projects\my-app-name\node_modules\typescript\lib\tsc.js:1755
            basePaths: getBasePaths(path
                                    ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 1.
Executing after-watch hook from C:\TFS Projects\my-app-name\hooks\after-watch\nativescript-dev-sass.js
Executing after-watch hook from C:\TFS Projects\my-app-name\hooks\after-watch\nativescript-dev-typescript.js

C:\TFS Projects\my-app-name>

**Comment by tsonevn** [comment]
Hi @narayansikarwar,
Excuse me for the delay in reply,
I tested further your case, while using `template tns-template-tab-navigation-ng`, however, I am still unable to recreate the same problem.
Were you able to solve this issue? If the problem still persists, try deleting node_modules, platforms and hooks folder from the project. Then run `npm install` command and try to transpile the files manually while running `tsc` command in the console. If the process completes successfully, run `tns run android`.

**Comment by tsonevn** [comment]
closing due to inactivity

**Comment by phatakrajan** [comment]
I am still facing this issue. Immediately after basic Nativescript installation and default template project, it fails while creating the build. Any solution?

**Comment by tsonevn** [comment]
HI @phatakrajan,
Can you send us the error log, which is thrown in the console as well as the exact steps, which you use, while creating and building the project? Also provide more info about your environment(NativeScript CLI, tns-android, tns-ios, tns-core-modules, node, npm, typescript versions).

**Comment by rachid-aachich** [comment]
Having the same issue:

Searching for devices...
Executing before-liveSync hook from C:\Users\sony\project\nativescript\hooks\before-liveSync\nativescript-angular-s
ync.js
Executing before-prepare hook from C:\Users\sony\project\nativescript\hooks\before-prepare\nativescript-dev-sass.js

Found peer node-sass
Executing before-prepare hook from C:\Users\sony\project\nativescript\hooks\before-prepare\nativescript-dev-typescr
ipt.js
Found peer TypeScript 2.3.4
Unable to apply changes on device: 534af2fc. Error is: TypeScript compiler failed with exit code 3221225477.
