### ISSUE TITLE
Error during tns run

### ISSUE THREAD

**Issue by sabadoc** [NativeScript/nativescript-angular#1140]
Hello, the console out this problem when  i launch tns run android.

Exception in thread "main" java.lang.ClassNotFoundException: org.nativescript.Process
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.ig.GetInterfaceNames.generateInterfaceNames(GetInterfaceNames.java:63)
        at com.ig.GetInterfaceNames.main(GetInterfaceNames.java:35)

node version: 6.12.2
tns doctor output: No9 issues were detected.
tns version: 3.4.0.

**Comment by NickIliev** [comment]
@sabadoc provide a sample project that can reproduce and as much as possible details about the issue so we could investigate further. 

Note: Running with `tns run android --log trace` will provide a more detailed log.

**Comment by sabadoc** [comment]
Hi @NickIliev, thanks but i found the solution. The problem was in the path beacause it had a strange characters.
