### ISSUE TITLE
Alert dialog inside ngOnInit and constructors in first route throws exception

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1394]
_From @ElecTreeFrying on June 19, 2018 19:13_

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

yes

### Tell us about the problem
I am getting this error then logging with alerts `alert('any-string')` inside constructors and ngOnInit, in `app/item/items.component.ts` and in `app.component.ts`. 

and in all routes after `"/"` only

```
const routes: Routes = [
    { path: "", redirectTo: "/a", pathMatch: "full" },
    { path: "a", component: aC },     // affected 
    { path: "b", component: bC }      // affected
    { path: "c", component: cC},      // affected
    { path: "c/:id", component: X},   // not affected
    { path: "d/e", component: X},     // not affected
    { path: "d/e/f/g", component: X},    // not affected
];
```
but is working perfectly fine with tap events `(tap)="anyFunction()"`

app
 | -> App_Resources
 | -> item
 | | -> item-detail.component.html
 | | -> item-detail.component.ts
 | | -> item.service.ts
 | | -> item.ts
 | | -> items.component.html
 | | -> items.component.ts
 -> app.component.html
 -> app.component.ts
 -> app.css
 -> app.module.ngfactory.d.ts
 -> app.module.ts
 -> app.routing.ts
 -> main.aot.ts
 -> main.ts
 -> package.json
 -> README.md

after the very first `successfully synced application org.nativescript.myApp` this error appears in CLI

```
An uncaught Exception occurred on "AsyncTask #1" thread.
java.lang.RuntimeException: An error occured while executing doInBackground()
	at org.nativescript.widgets.image.AsyncTask$3.done(AsyncTask.java:326)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at org.nativescript.widgets.image.AsyncTask$SerialExecutor$1.run(AsyncTask.java:256)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: not a directory: /storage/emulated/0/Android/data/org.nativescript.myapp/cache/http
	at org.nativescript.widgets.image.DiskLruCache.deleteContents(DiskLruCache.java:257)
	at org.nativescript.widgets.image.DiskLruCache.delete(DiskLruCache.java:713)
	at org.nativescript.widgets.image.DiskLruCache.open(DiskLruCache.java:328)
	at org.nativescript.widgets.image.Fetcher.initDiskCacheInternal(Fetcher.java:92)
	at org.nativescript.widgets.image.Worker$CacheAsyncTask.doInBackground(Worker.java:502)
	at org.nativescript.widgets.image.Worker$CacheAsyncTask.doInBackground(Worker.java:493)
	at org.nativescript.widgets.image.AsyncTask$2.call(AsyncTask.java:313)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): 4.1.3
- Plugin(s): 4.1.3

### Please tell us how to recreate the issue in as much detail as possible.

Step to reproduce:
1. `tns create myApp --ng;cd myApp;tns platform add android;tns run android`

_Copied from original issue: NativeScript/nativescript-cli#3693_

**Comment by NickIliev** [comment]
@ElecTreeFrying I've managed to reproduce the issue, but with different error output so I am marking this one as a bug.

Steps to reproduce:
- Use [this test application](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-angular/issue-1394)
- On the initial page the alert is throwing (on my side) with the following error:
```
JS: ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
JS:     android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:224)
JS:     android.app.AlertDialog$Builder.<init>(AlertDialog.java:459)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:954)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:946)
JS:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
JS:     android.app.Activity.performCreate(Activity.java:7174)
JS:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThre...
```

**Comment by NickIliev** [comment]
@ElecTreeFrying after some additional investigation it appears that the case is expected as the native application is not fully initialized during the Angular events. This said it is expected for the dialogs to crash as there is no NativeScript's page which is a must for the `dialogs` module. 

The solution is pretty straightforward - use the NativeScript's application event to load your dialogs (e.g. `loaded` event).

For example:
```TypeScript
import { Page } from "tns-core-modules/ui/page";

export class ItemComponent implements OnInit {
    subs: any;

    constructor(private _page: Page) { 
        this.subs = this._page.on("loaded", () => {
           alert("ALERT ALERT ALERT");
        ])
    }

}
```

It is a good practice to remove the subscription to the loaded event when it is not needed anymore.
```
ngOnDestroy() {
    this._page.off(this.subs);
}
```

That said, we could also use any `loaded` event of any NativeScript layout
```XML
<StackLayout (loaded)="onStackLoaded($event)">
```

```TypeScript
onStackLoaded(args: EventData) {
    alert("ALERT ALERT ALERT");
}
```

Adding this [as a TODO in the docs repository](https://github.com/NativeScript/docs/issues/1240) and closing the issue as the problem should be handled in the abgove ways.
