### ISSUE TITLE
Nativescript-angular Radsidedrawer message in console

### ISSUE THREAD

**Issue by yamchi** [NativeScript/nativescript-angular#1400]
Hi ! after installing RadsideDrawer in my app.. i got a weird message in console

```
06-23 10:59:13.432 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
06-23 10:59:13.432 29485 29485 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
06-23 10:59:13.432 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
06-23 10:59:13.432 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:970)
06-23 10:59:13.432 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:954)
06-23 10:59:13.432 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:946)
06-23 10:59:13.447 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
06-23 10:59:13.447 29485 29485 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
06-23 10:59:13.447 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
06-23 10:59:13.447 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:970)
06-23 10:59:13.447 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:954)
06-23 10:59:13.447 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:946)
06-23 10:59:13.454 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
06-23 10:59:13.454 29485 29485 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
06-23 10:59:13.454 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
06-23 10:59:13.454 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:970)
06-23 10:59:13.454 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:954)
06-23 10:59:13.454 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:946)
06-23 10:59:13.460 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
06-23 10:59:13.460 29485 29485 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
06-23 10:59:13.460 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
06-23 10:59:13.460 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:970)
06-23 10:59:13.460 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:954)
06-23 10:59:13.460 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:946)
06-23 10:59:13.465 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
06-23 10:59:13.465 29485 29485 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
06-23 10:59:13.465 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
06-23 10:59:13.465 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:970)
06-23 10:59:13.465 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:954)
06-23 10:59:13.465 29485 29485 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:946)
```

But Everything works fine, I'm just worried about this message in console what it might cause in my project in the near future.. Thanks !

P.S. my radsidedrawer is not in the root.

**Comment by tsonevn** [comment]
Hi @yamchi,
Please provide some more info about your environment (NativeScript CLI, tns-core-modules, tns-ios, tns-android, nativescript-angular versions). Does this happen on Android only or on iOS as well? 
It will help if you can send us sample project, which can be used for debugging.

In the meantime, you can try deleting `node_modules` and `platforms` folders and rebuild the project.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#711
