### ISSUE TITLE
ActtionBar cannot be wrapped into its own component

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1472]
_From @IAMtheIAM on August 3, 2018 18:0_

If I want to create a reusable action bar component like so:
```
//home.component.ts
<header [title]="'My Course Plan'"></header>
```
where I pass a string which becomes the value for action:

```
//header.component.html
<ActionBar class="action-bar">
    <Label class="action-bar-title"
        [text]="title"
        (tap)="logout()"></Label>
</ActionBar>
```

```
//header.component.ts
import { Component, Input } from '@angular/core';
import { LogoutService } from "../../../services/logout.service";

// import './header.component.scss';
// app

@Component({
    moduleId: module.id,
    selector: 'header',
    templateUrl: './header.component.html',
    styleUrls: [ './header.component.scss' ]
})
export class HeaderComponent {
    @Input() title: string;

    constructor(private logoutService: LogoutService) {
    }

    logout() {
        this.logoutService.logout(false);
    }
}

```

It does not work. It renders the default action bar with the word `nativescript` left aligned, the same as if I did not put the custom component there at all.

Why does it not understand this component? I must be misunderstanding something because this setup works for most components in angular.

TNS 4.1.1
NativeScript angular 6.1.0-rc.0
Android API 26

_Copied from original issue: NativeScript/NativeScript#6149_

**Comment by tsonevn** [comment]
Hi @IAMtheIAM,
Thank you for the provided code snippets.
I tested the scenario with ActionBar wrapped into a custom component, however, was unable to recreate the problem. I am attaching the sample project, which I used for testing. Please review it and make the needed changes, which will allow us to reproduce the issue.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2261447/Archive.zip)

**Comment by IAMtheIAM** [comment]
Hi, thanks for that demo. It is in fact working, so I need to diagnose why my app is not because it appears to be implemented similarly. I will update when I find out more.

**Comment by IAMtheIAM** [comment]
[nativescript-header.zip](https://github.com/NativeScript/nativescript-angular/files/2263673/nativescript-header.zip)
Hi, I stripped down everything from my app except one component, and I still had the same issue. Weird because I downloaded your sample and it works fine.

I cannot see what is causing it to not work, could you take a look at `app.component.html` and `directory.component.html`? Thank you.

**Comment by tsonevn** [comment]
Hi @IAMtheIAM,
Thank you for the attached project.
I tried to build it on my side, however the project crashed on startup with the following error:
```
System.err: ReferenceError: ENV is not defined
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/edu.tccd.pathways/files/app/assets/environments/env-config.js', line: 50, column: 19
System.err: 	Frame: function:'', file:'file:///data/data/edu.tccd.pathways/files/app/assets/environments/env-config.js', line: 69, column: 2
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/edu.tccd.pathways/files/app/app/services/logout.service.js', line: 17, column: 20
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/edu.tccd.pathways/files/app/app/services/index.js', line: 6, column: 10
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/edu.tccd.pathways/files/app/app/app.module.js', line: 12, column: 18
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/edu.tccd.pathways/files/app/main.js', line: 4, column: 20
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:542)
System.err: 	at com.tns.Runtime.run(Runtime.java:534)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
System.err: 	... 8 more
```
Can you check the project and verify what can cause this error? Also, Are there any specific steps, which I should follow, while building the project?

Regarding the issue, I reviewed the code in app.componet.html and notice that you are defining a `Page` manually in the HTML. The Page should be set in the XML only in the non-Angular NativeScript project. In NS Angular, it will be added automatically. You should remove it from the HTML code. Most probably, this definition of the Page is causing the issue on your side. Also, I would suggest reviewing our tutorial [here](https://docs.nativescript.org/angular/start/introduction#step-1-nativescript-playground), where are described the basic concept of creating a NativeScript Angular app.

Regards,
@tsonevn

**Comment by IAMtheIAM** [comment]
That is weird, it compiles for me. 

I tried removing the <Page> in the app component html but it resulted in the same issue. I will try to see why the app did not build for you and upload again.

**Comment by tsonevn** [comment]
Hi @IAMtheIAM,
Were you able to recreate the issue in sample project?
