### ISSUE TITLE
Can't resolve all parameters for ApplicationModule

### ISSUE THREAD

**Issue by noomieware** [NativeScript/nativescript-angular#1540]
### Make sure to check the existing issues in this repository 

None found.

### Which platform(s) does your issue occur on?
- Both 
- iOS12 / Android 8.1.0
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: $ tns --version -> 4.2.4
- Cross-platform modules: "tns-core-modules@4.2.1",
- Runtime(s):     "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }

### Please, tell us how to recreate the issue in as much detail as possible. 

Issue shows up, if I update @angular/* to >6.1.8. No error with 6.1.0 dependencies. 

an npm update installed newer @angular packages, due to having ~6.1.0 in package.json (as it is set by cli). With that in place I got:

```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.charenjiapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Can't resolve all parameters for ApplicationModule: (?).
System.err: File: "file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 11175, column: 16
```

I first checked for missing DI imports and circular references, but everything was / is fine here, and worked without any changes before. A downgrade of the @angular packages solved it again.

### full stacktrace

```
ActivityManager: Launch timeout has expired, giving up wake lock!
10-04 09:23:59.174  7551  7551 E AndroidRuntime:        at com.tns.Runtime.callJSMethodNative(Native Method)
10-04 09:23:59.174  7551  7551 E AndroidRuntime:        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-04 09:23:59.174  7551  7551 E AndroidRuntime:        at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-04 09:23:59.174  7551  7551 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-04 09:23:59.174  7551  7551 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-04 09:23:59.174  7551  7551 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.charenjiapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Can't resolve all parameters for ApplicationModule: (?).
System.err: File: "file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 11175, column: 16
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err:     Frame: function:'syntaxError', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 1098, column: 21
System.err:     Frame: function:'CompileMetadataResolver._getDependenciesMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10987, column: 39
System.err:     Frame: function:'CompileMetadataResolver._getTypeMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10880, column: 30
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10748, column: 28
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleSummary', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10558, column: 39
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10645, column: 59
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10623, column: 53
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleSummary', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10558, column: 39
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10645, column: 59
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10623, column: 53
System.err:     Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23932, column: 55
System.err:     Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23913, column: 40
System.err:     Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23873, column: 41
System.err:     Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 202, column: 35
System.err:     Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4417, column: 29
System.err:     Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/nativescript-angular/platform-common.js', line: 75, column: 66
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/nativescript-angular/platform-common.js', line: 128, column: 19
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err:     Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 884, column: 17
System.err:     Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 817, column: 28
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 691, column: 14
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Can't resolve all parameters for ApplicationModule: (?).
System.err: File: "file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 11175, column: 16
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err:     Frame: function:'syntaxError', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 1098, column: 21
System.err:     Frame: function:'CompileMetadataResolver._getDependenciesMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10987, column: 39
System.err:     Frame: function:'CompileMetadataResolver._getTypeMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10880, column: 30
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10748, column: 28
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleSummary', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10558, column: 39
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10645, column: 59
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10623, column: 53
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleSummary', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10558, column: 39
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10645, column: 59
System.err:     Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10623, column: 53
System.err:     Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23932, column: 55
System.err:     Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23913, column: 40
System.err:     Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23873, column: 41
System.err:     Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 202, column: 35
System.err:     Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4417, column: 29
System.err:     Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/nativescript-angular/platform-common.js', line: 75, column: 66
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/nativescript-angular/platform-common.js', line: 128, column: 19
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err:     Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 884, column: 17
System.err:     Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 817, column: 28
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 691, column: 14
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err:     at android.app.Activity.performCreate(Activity.java:7009)
System.err:     at android.app.Activity.performCreate(Activity.java:7000)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
System.err:     ... 9 more
```

I choose nativescript-angular as issue target, as it seems there is some incompatibility between nativescript and angular in that case. If I was wrong, please excuse me. 

Thx.

**Comment by tsonevn** [comment]
Hi @noomieware,
Can you share with us a sample project, which can be used for recreating the issue?

**Comment by NickIliev** [comment]
@noomieware are you by chance using Webpack bundling? If so please notice this issue (which is fixed with the next `nativescript-dev-webpack` and `nativescript-angular`) or try [the following solution](https://github.com/NativeScript/nativescript-dev-webpack/issues/660#issuecomment-422711983).

Closing this one due to inactivity but please do let us know if you need further assistance.
