### ISSUE TITLE
Unit testing: Fails when component depends on the router

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-angular#1549]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.3
 - Cross-platform modules: 4.2.0
 - Android Runtime: 4.2.0
 - iOS Runtime: N/A
 - Plugin(s): N/A
 - NativeScript-Angular: 6.1.0
 - Angular: 6.1.9
 
**Describe the bug**

I want to implement unit tests of the components in our project.
The components that injects dependencies from `@angular/router` and `nativescript-angular/router` fails with an error like this:

```bash
        Failed: StaticInjectorError(DynamicTestModule)[LocationStrategy -> PlatformLocation]: 
          StaticInjectorError(Platform: core)[LocationStrategy -> PlatformLocation -> InjectionToken DocumentToken]: 
            document is not defined
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'LocationStrategy', Function ] })
            at <Jasmine>
            at _document (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/platform-browser/bundles/platform-browser.umd.js:1995:9)
            at resolveToken (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:1376:113)
            at tryResolveToken (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:1324:20)
            at resolveToken (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:1363:35)
            at tryResolveToken (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:1324:20)
            at StaticInjector.get (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:1221:24)
            at resolveToken (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:1380:28)
            at tryResolveToken (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:1324:20)
            at StaticInjector.get (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:1221:24)
            at resolveNgModuleDep (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:8400:33)
            at _callFactory (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:8468:32)
            at _createProviderInstance (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:8420:30)
            at initNgModule (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:8350:36)
            at new NgModuleRef_ (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:9076:13)
            at createNgModuleRef (file:///data/data/org.nativescript.tnsngtesting/files/app/tns_modules/@angular/core/bundles/core.umd.js:9065:16)
```

**To Reproduce**

* Create a new nativescript-angular project and setup testing (I used jasmine as the framework).
* Write a test for a component that depends on the router.
* Get: StaticInjectorError: InjectionToken DocumentToken. "document is not defined".

**Expected behavior**
Component to be loaded so it can be tested.

**Sample project**

https://github.com/m-abs/ns-debugging/tree/master/tns-ng-testing

To run the sample project:
* clone https://github.com/m-abs/ns-debugging
* cd ns-debugging/tns-ng-testing
* run: npm i && tns test android

The test can be seen here:
https://github.com/m-abs/ns-debugging/blob/master/tns-ng-testing/app/tests/test-main.ts

Note: The `RouterTestingModule` was added to the imports.

**Additional context**

**Comment by m-abs** [comment]
Temp workaround:
Provide DOCUMENT > NativeScriptDocument in nsTestBedBeforeEach
```typescript
  beforeEach(
    nsTestBedBeforeEach(
      [MyComponent],
      [
  {
    // DOCUMENT must be injected manually for RouterTestingModule to work.
    provide: DOCUMENT,
    useClass: NativeScriptDocument,
  },
],
    )
)
```

**Comment by jitendraashutec** [comment]
@m-abs  what you mean by NativeScriptDocument ? what is will contain ?

**Comment by m-abs** [comment]
> @m-abs what you mean by NativeScriptDocument ? what is will it contain?

This is a really old issue. I don't know it the workaround is needed anymore.

`NativeScriptDocument` is from here: 
https://github.com/NativeScript/nativescript-angular/blob/951909aeda405d8cf4849609e14e400bd19ddf60/nativescript-angular/platform-common.ts#L100
