### ISSUE TITLE
[iOS] Could not find module './' or [Android] Failed to find module: "./"

### ISSUE THREAD

**Issue by alonstar** [NativeScript/nativescript-angular#1565]
I followed the introduction (https://docs.nativescript.org/code-sharing/intro) to create a new code sharing project : 

> ng new -c=@nativescript/schematics sass-project --shared --style=scss

Then tried to run on Android & iOS, but it can't work on both platform, how do I fix it?

**Environment**
package.json

```
{
  "name": "sass-project",
  "nativescript": {
    "id": "org.nativescript.sassproject",
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android --bundle",
    "ios": "tns run ios --bundle"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "core-js": "^2.5.4",
    "nativescript-angular": "~6.1.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.0.0",
    "tns-core-modules": "~4.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "^6.2.0",
    "@angular/compiler-cli": "~6.0.3",
    "@angular-devkit/build-angular": "^0.8.0",
    "@nativescript/schematics": "~0.3.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.16.0",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "nativescript-dev-sass": "~1.6.0"
  }
}
```

tsconfig.json
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom",
            "es6",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "src/*"
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "**/*.tns.ts",
        "**/*.android.ts",
        "**/*.ios.ts",
        "**/*.spec.ts"
    ]
}
```
tsconfig.tns.json
```
{
    "extends": "./tsconfig",
    "compilerOptions": {
        "module": "es2015",
        "moduleResolution": "node"
    }
}

```

Android:

> 
> System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
> System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4347)
> System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
> System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
> System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
> System.err:     at android.os.Looper.loop(Looper.java:136)
> System.err:     at android.app.ActivityThread.main(ActivityThread.java:5017)
> System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
> System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
> System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
> System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
> System.err:     at dalvik.system.NativeStart.main(Native Method)
> System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
> System.err:     at com.tns.Module.bootstrapApp(Module.java:311)
> System.err:     at com.tns.Runtime.run(Runtime.java:544)
> System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
> System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
> System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
> System.err:     ... 10 more
> System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
> System.err:     at com.tns.Module.resolvePathHelper(Module.java:146)
> System.err:     at com.tns.Module.bootstrapApp(Module.java:309)

iOS

> ***** Fatal JavaScript exception - application has been terminated. *****
> Native stack trace:
> 1   0x10a743c1f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
> 2   0x10a778caf -[TNSRuntime executeModule:referredBy:]
> 3   0x10a1aa1f3 main
> 4   0x10e007551 start
> JavaScript stack trace:
> 1   @[native code]
> 2   promiseReactionJob@[native code]
> JavaScript error:
> [native code]: JS ERROR Error: Could not find module './'. Computed path '/Users/shelly.chen/Library/Developer/CoreSimulator/Devices/374D0919-5325-40C5-9878-8748A08A136A/data/Containers/Bundle/Application/EB8A1BCF-B3F6-4705-BD0D-80AD17337B76/sass-project.app/app'.

**Comment by alonstar** [comment]
enviroment : 
macOS Mojave 10.14
tns  4.2.4
node 8.12.0
