### ISSUE TITLE
webpack uglify TypeError: this.pageRoute.activatedRoute.switchMap is not a function

### ISSUE THREAD

**Issue by PraktikerNeosoft** [NativeScript/nativescript-angular#1655]
I use angular 7 and tns run android is fine but if tns run android --bundle --env.aot --env.uglify I get this error. Please help me because I have no idea what is the problem. If I remove uglify then run app.
Lot of THNX
Miklos

```
ERROR Error: Uncaught (in promise): TypeError: this.pageRoute.activatedRoute.switchMap is not a function
JS: TypeError: this.pageRoute.activatedRoute.switchMap is not a function
JS:     at new n (file:///data/data/hu.praktiker/files/app/bundle.js:1:13973)
JS:     at Mv (file:///data/data/hu.praktiker/files/app/vendor.js:1:191561)
JS:     at Rv (file:///data/data/hu.praktiker/files/app/vendor.js:1:190813)
JS:     at kv (file:///data/data/hu.praktiker/files/app/vendor.js:1:190133)
JS:     at hm (file:///data/data/hu.praktiker/files/app/vendor.js:1:201899)
JS:     at lm (file:///data/data/hu.praktiker/files/app/vendor.js:1:200753)
JS:     at ly (file:///data/data/hu.praktiker/files/app/vendor.js:1:218942)
JS:     at Object.Im [as createRootView] (file:///data/data/hu.praktiker/files/app/vendor.js:1:211660)
JS:     at t.create (file:///data/data/hu.praktiker/files/app/vendor.js:1:179943)
JS:     at t.create (file:///data/data/hu.praktiker/files/app/vendor.js:1:77353)
JS:     at e.createComponent (file:///data/data/hu.praktiker/files/app/vendor.js:1:182106)
```

package.json

```
{
  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "fs.realpath": "~1.0.0",
    "nativescript-angular": "~7.0.0",
    "nativescript-background-http": "~3.3.1",
    "nativescript-barcodescanner": "~2.7.9",
    "nativescript-camera": "~4.1.1",
    "nativescript-directions": "~1.3.0",
    "nativescript-geolocation": "~4.3.1",
    "nativescript-google-maps-sdk": "~2.6.1",
    "nativescript-intl": "~3.0.0",
    "nativescript-mapbox": "~4.4.0",
    "nativescript-onesignal": "github:PraktikerNeosoft/nativescript-onesignal",
    "nativescript-permissions": "~1.2.3",
    "nativescript-phone": "~1.4.0",
    "nativescript-plugin-firebase": "~7.4.3",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "~5.0.0",
    "nativescript-ui-sidedrawer": "~5.0.1",
    "nativescript-zxing": "~1.5.7",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.3.3",
    "rxjs-compat": "~6.3.3",
    "tns-core-modules": "~5.0.5",
    "tns-platform-declarations": "~5.0.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.0.0",
    "@ngtools/webpack": "~7.0.0",
    "babel-traverse": "~6.26.0",
    "babel-types": "~6.26.0",
    "babylon": "~6.18.0",
    "filewalker": "~0.1.3",
    "lazy": "~1.0.11",
    "nativescript-css-loader": "~0.26.1",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.8",
    "nativescript-dev-webpack": "~0.18.2",
    "sass": "~1.15.2",
    "typescript": "~3.1.1"
  },
}

```

**Comment by nikoTM** [comment]
I am guessing that you should just `pipe` the `switchMap`, as in:

`this.pageRoute.activatedRoute.pipe(switchMap(...))`

**Comment by PraktikerNeosoft** [comment]
> I am guessing that you should just `pipe` the `switchMap`, as in:
> 
> `this.pageRoute.activatedRoute.pipe(switchMap(...))`

Thanx. No build error but if open app get white blank page. :(
