### ISSUE TITLE
*ngIf inside modal causes crash

### ISSUE THREAD

**Issue by jeffswitzer** [NativeScript/nativescript-angular#1715]
**Describe the bug**
When opening a modal that has an *ngIf inside it, the following runtime error is thrown:
```
[XT1585]: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'parent' of undefined
[XT1585]: at Object.onInvoke (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bundles/core.umd.js:16201:37)
[XT1585]: at Zone.run (file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:43)
[XT1585]: at file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:883:34
[XT1585]: at ZoneDelegate.invoke (file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:26)
[XT1585]: TypeError: Cannot read property 'parent' of undefined
[XT1585]: at file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-angular/directives/dialogs.js:104:31
[XT1585]: at ZoneDelegate.invokeTask (fi...
[XT1585]: at ZoneDelegate.invoke (file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:387:32)
```

**To Reproduce**
Open the native script program I've linked to below and click the "Show Modal" button

**Sample project**
https://play.nativescript.org/?template=play-ng&id=Ys1exJ&v=1

So far I've only tried this on android.

**Comment by tsonevn** [comment]
Hi @jeffswitzer,
You can have only one root container in the HTML. If you wrap the StackLayouts in `test-modal.html` file in a single container, the problem will disappear. For example:
 ```
<StackLayout>
    <StackLayout *ngIf="true">
        <Label text="Welcome to modal 1!"></Label>
        <Button text="close" (tap)="close()"></Button>
    </StackLayout>
    <StackLayout *ngIf="false">
        <Label text="Welcome to modal 2!"></Label>
        <Button text="close" (tap)="close()"></Button>
    </StackLayout>
</StackLayout>
```
Check out the [sample project](https://play.nativescript.org/?template=play-ng&id=Ys1exJ&v=2) here as well.

**Comment by jeffswitzer** [comment]
@tsonevn Thanks for looking at it, works as you say.
