### ISSUE TITLE
Cannot read property 'kill' of undefined

### ISSUE THREAD

**Issue by Rugved** [NativeScript/nativescript-angular#1752]
**Project Dependencies** 

Trying to add NativeScript inside Existing Angular Project. Getting below error

    "@angular/animations": "^7.2.7",
    "@angular/common": "^7.2.7",
    "@angular/compiler": "^7.2.7",
    "@angular/core": "^7.2.7",
    "@angular/forms": "^7.2.7",
    "@angular/http": "^7.2.7",
    "@angular/platform-browser": "^7.2.7",
    "@angular/platform-browser-dynamic": "^7.2.7",
    "@angular/platform-server": "^7.2.7",
    "@angular/router": "^7.2.7",
    "@nativescript/schematics": "^0.5.1",
    "@ng-bootstrap/ng-bootstrap": "^4.0.1",
    "bootstrap": "^4.1.3",
    "c3": "^0.6.11",
    "core-js": "^2.6.5",
    "d3": "^5.7.0",
    "jquery": "^3.3.1",
    "nativescript-angular": "~7.2.0",
    "nativescript-theme-core": "~1.0.4",
    "ng2-file-upload": "^1.3.0",
    "ng2-pdf-viewer": "^5.2.3",
    "popper.js": "^1.14.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "tns-core-modules": "~5.2.0",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "zone.js": "^0.8.29"

**Describe the bug**
When running command "TNS Preview --bundle" inside VS code I get following error

**Error**

```
webpack is watching the files…

TypeError: Cannot read property 'kill' of undefined
    at stopWebpackForPlatform (C:\tfs\Users\Play\WebApp\ClientApp\node_modules\nativescript-dev-webpack\lib\compiler.js:176:20)
    at process.stopWebpackCompiler (C:\tfs\Users\Play\WebApp\ClientApp\node_modules\nativescript-dev-webpack\lib\compiler.js:128:9)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.exit (internal/process.js:157:15)
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:78:21)
    at Generator.next (<anonymous>)
    at C:\Users\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:3:12)
    at process.handler (C:\Users\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:60:30)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
Stopping webpack watch
```

**Comment by NickIliev** [comment]
@Rugved you can't add the NativeScript framework for mobile development directly in an Angular web application. If you want to create both mobile and web version of your project use the Code Sharing functionality - more about Code Sharing [here](https://docs.nativescript.org/angular/code-sharing/intro)

**Comment by Rugved** [comment]
I did run ng add @nativescript/schematics to convert my app for native script and did have it working before. You are right, I had some components and moduels in app.module.tsn.ts file which were not converted so removing them worked. Thanks again
