### ISSUE TITLE
tns run android --bundle fails with System.err: TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by satishblr** [NativeScript/nativescript-angular#1754]
**Environment**
√ Component nativescript has 5.2.0 version and is up to date.
√ Component tns-core-modules has 5.2.1 version and is up to date.
√ Component tns-android has 5.2.1 version and is up to date.
√ Component tns-ios has 5.2.0 version and is up to date.
 
**Describe the bug**
I am creating a shared angular app which can be run as web app and ios/android. my project runs good using ng serve but when i run on android i get this error on the emulator

```
Webpack build done!
Hook skipped because either bundling or livesync is in progress.
Hook skipped because either bundling or livesync is in progress.
Preparing project...
Project successfully prepared (Android)
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from C:\Satish\quilink\construction\tsmean\frontend\App_Resources\Android\app.gradle
         + using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\Satish\quilink\construction\tsmean\frontend\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
(node:10848) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Project successfully built.
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.tsmean/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: TypeError: Cannot read property 'create' of undefined
System.err: File: "file:///data/data/org.nativescript.tsmean/files/app/vendor.js, line: 12294, column: 14
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.tsmean/files/app/vendor.js', line: 12294, column: 15
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.navigate', file:'file:///data/data/org.nativescript.tsmean/files/app/vendor.js', line: 19881, column: 30
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.tsmean/files/app/vendor.js', line: 21271, column: 30
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.tsmean/files/app/vendor.js', line: 21115, column: 14
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.tsmean/files/app/vendor.js', line: 19032, column: 25
System.err:
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
```

**To Reproduce**
upgraded my existing web app to shared app

**Comment by NickIliev** [comment]
@satishblr make sure you are having the latest versions of nativescript-schematics and the angular CI (see t[his documentation section](https://docs.nativescript.org/angular/code-sharing/creating-a-new-project#prerequisites)) and recreate your code shared project. Also, you can try a clean rebuild by removing the `platforms` folder of your mobile app.
