### ISSUE TITLE
tns build android - Cannot read property 'create' of undefined / Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by OysteinAmundsen** [NativeScript/nativescript-angular#1766]
**Environment**

```
Angular CLI: 7.3.6
Node: 11.4.0
OS: win32 x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cdk                      7.3.5
@angular/cli                      7.3.6
@angular/material                 7.3.5
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0


√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.2.3 and the latest available version is 5.2.4.
√ Component tns-core-modules has 5.2.2 version and is up to date.
√ Component tns-android has 5.2.1 version and is up to date.
× Component tns-ios is not installed.
```
 - NativeScript-Angular: 7.2.3

**Describe the bug**

In short, I experience the same error message as https://github.com/NativeScript/nativescript-angular/issues/1754, but instead of commenting on that issue I decided to create a new one because I'm not entirely sure that the cause is the same. I get slightly different errors depending on which config I'm trying to run.

When I `tns run android --bundle --env.aot`, I get: 
> TypeError: Cannot read property 'create' of undefined

By inspecting line 12322 in my vendor.js, it seams as it tries to create either a component or a module, but I cannot figure out which one specifically it has problems with. Is there a way to list out the entries it tries to instantiate?

```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aibel.ailm/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: TypeError: Cannot read property 'create' of undefined
System.err: File: "file:///data/data/com.aibel.ailm/files/app/vendor.js, line: 12322, column: 14
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 12322, column: 15
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.navigate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 19910, column: 30
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 21300, column: 30
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 21144, column: 14
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 19060, column: 25
System.err:
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: TypeError: Cannot read property 'create' of undefined
System.err: File: "file:///data/data/com.aibel.ailm/files/app/vendor.js, line: 12322, column: 14
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 12322, column: 15
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.navigate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 19910, column: 30
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 21300, column: 30
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 21144, column: 14
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 19060, column: 25
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err:     at android.app.Activity.performCreate(Activity.java:7009)
System.err:     at android.app.Activity.performCreate(Activity.java:7000)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
System.err:     ... 9 more
```

When I run `tns run android --bundle`, I get: 
> Error: Expected 'styles' to be an array of strings.

Which 'styles' is it referring to? I only use styleUrls in my components. Is this 'styles' object something outside angular? If so, what is it? I beleive that this might be the source of my troubles.

```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aibel.ailm/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Expected 'styles' to be an array of strings.
System.err: File: "file:///data/data/com.aibel.ailm/files/app/vendor.js, line: 40948, column: 12
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 172891, column: 33
System.err:     Frame: function:'assertArrayOfStrings', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 40948, column: 19
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54400, column: 13
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 55045, column: 28
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 55036, column: 31
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentsFromProvider', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 55035, column: 30
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 55008, column: 138
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getProvidersMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54971, column: 19
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54973, column: 23
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getProvidersMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54971, column: 19
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54594, column: 118
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54585, column: 49
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54520, column: 35System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54607, column: 55
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54585, column: 49
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 61994, column: 51
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 61975, column: 36
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 61935, column: 37
System.err:     Frame: function:'push.../../../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 136854, column: 31
System.err:     Frame: function:'compileNgModuleFactory__PRE_R3__', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 81065, column: 21
System.err:     Frame: function:'push.../../../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 81248, column: 16
System.err:     Frame: function:'_bootstrapper', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 168206, column: 35
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 168269, column: 19
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 196093, column: 23
System.err:     Frame: function:'notifyLaunch', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 214081, column: 17
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 214011, column: 28
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 213870, column: 14
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 211786, column: 25
System.err:
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Expected 'styles' to be an array of strings.
System.err: File: "file:///data/data/com.aibel.ailm/files/app/vendor.js, line: 40948, column: 12
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 172891, column: 33
System.err:     Frame: function:'assertArrayOfStrings', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 40948, column: 19
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54400, column: 13
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 55045, column: 28
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 55036, column: 31
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentsFromProvider', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 55035, column: 30
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 55008, column: 138
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getProvidersMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54971, column: 19
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54973, column: 23
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getProvidersMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54971, column: 19
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54594, column: 118
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54585, column: 49
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54520, column: 35System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54607, column: 55
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 54585, column: 49
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 61994, column: 51
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 61975, column: 36
System.err:     Frame: function:'push.../../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 61935, column: 37
System.err:     Frame: function:'push.../../../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 136854, column: 31
System.err:     Frame: function:'compileNgModuleFactory__PRE_R3__', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 81065, column: 21
System.err:     Frame: function:'push.../../../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 81248, column: 16
System.err:     Frame: function:'_bootstrapper', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 168206, column: 35
System.err:     Frame: function:'', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 168269, column: 19
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 196093, column: 23
System.err:     Frame: function:'notifyLaunch', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 214081, column: 17
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 214011, column: 28
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 213870, column: 14
System.err:     Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/com.aibel.ailm/files/app/vendor.js', line: 211786, column: 25
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err:     at android.app.Activity.performCreate(Activity.java:7009)
System.err:     at android.app.Activity.performCreate(Activity.java:7000)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
System.err:     ... 9 more
```

And if I run `tns run android`, it seems to want to include the whole world in the compilation. I first get about a million messages similar to this one (while the application builds):
```
platforms/android/app/src/main/assets/app/tns_modules/@angular/material/schematics/ng-generate/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts(15,78): error TS1109: Expression expected.
```
... which is annoying since none of my *.tns.ts files refer to @angular/material at all. Then on deployment and application start, I get this one:

```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err:     at com.tns.Module.bootstrapApp(Module.java:311)
System.err:     at com.tns.Runtime.run(Runtime.java:615)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
System.err:     ... 8 more
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
System.err:     at com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     at com.tns.Module.bootstrapApp(Module.java:309)
System.err:     ... 12 more
```
Which might indicate that it is trying to use untranspiled code. 

What can I do to make the thing build? 

**Additional context**

My client will not allow me to publish the code. But I can say that I have not changed the default `webpack.config` which was created when I added the nativescript schematic to my angular project.

**Comment by tokiroto** [comment]
I have exact the same issue. Migrated project from web to shared, and can't start it. Default webpack, latest nativescript and angular related component versions. But when run:
`tns debug android` - can't find entry point;
`tns debug android --bundle` - simply error, can't start activity, without any distinct clue.
Would be nice if there can be found a solution.
P.S. When I take original "tour of heroes" project (https://angular.io/tutorial/toh-pt0) with latest everything, it also doesn't run under `tns debug android` with "can't find entry point", while works with `tns debug android --bundle`.

**Comment by NickIliev** [comment]
@OysteinAmundsen if possible please provide a sample project that we could test.

Meanwhile, check if you are passing an **array** of CSS file path strings and not directly the CSS file path string in each `styleUrls `

e.g. it should be
```TS
styleUrls : ["my-styles.css"]
```

and styleUrls 
```TS
styleUrls : "my-styles.css"
```

**Comment by OysteinAmundsen** [comment]
I'm sorry. My client does not allow me to post any code. 

The issue is resolved for my case. Don't know what was wrong, but I went back in git history to a point where this ran and patched in my changes. There were no instances where `stylesUrls` did not use an array of files anywhere in my code.

**Comment by zeeshan-mehdi** [comment]
i am having the same issue

![image](https://user-images.githubusercontent.com/31466216/63219210-4cd02a80-c186-11e9-9ad9-a52b371ccebe.png)
![image](https://user-images.githubusercontent.com/31466216/63219212-548fcf00-c186-11e9-94e9-9f6b24b959c5.png)
