### ISSUE TITLE
preview gives error cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by ray1618** [NativeScript/nativescript-angular#1823]
I use Windows 10 and fully installed the latest nativescript version 5.4.0 
$ tns doctor says I'm ready to run and all is ok.

But when I run
$tns preview
I get the following error in the console:

TypeError: Cannot read property 'hasOwnProperty' of null
at data.filter.el (C:\Users\ray\AppData\Roaming\npm\node_modules\nativescript\lib\common\logger\logger.js:135:76)
    at Array.filter (<anonymous>)
    at Logger.getLogOptionsForMessage (C:\Users\ray\AppData\Roaming\npm\node_modules\nativescript\lib\common\logger\logger.js:135:34)
    at Logger.logMessage (C:\Users\ray\AppData\Roaming\npm\node_modules\nativescript\lib\common\logger\logger.js:120:30)
    at Logger.trace (C:\Users\ray\AppData\Roaming\npm\node_modules\nativescript\lib\common\logger\logger.js:80:14)
    at HttpClient.getErrorMessage (C:\Users\ray\AppData\Roaming\npm\node_modules\nativescript\lib\common\http-client.js:223:26)
    at Request.requestObj.on (C:\Users\ray\AppData\Roaming\npm\node_modules\nativescript\lib\common\http-client.js:112:47)
    at Request.emit (events.js:180:13)
    at Request.onRequestError (C:\Users\ray\AppData\Roaming\npm\node_modules\nativescript\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)

**Comment by tsonevn** [comment]
Hi @ray1618 
I tested the `tns preview` command on my side within an NS Angular project, however, was unable to recreate the issue. Can you send us a sample project, which can be used for recreating the problem?

**Comment by JarriddW** [comment]
I am having this same issue, cant seem to get it working.

**Comment by ray1618** [comment]
Hi Jarrid,
Where dit you put the if statement?

**Comment by prabh08** [comment]
I am facing the same issue. Please help.

**Comment by tsonevn** [comment]
Hi all,
Can you check if you will be able to recreate the issue while using the latest CLI `5.4.1`?
Also, can you send us a sample project, which can be used for recreating the problem?

**Comment by ray1618** [comment]
Hi this issue seems to be solved in the latest version. I installed v5.4.2 today and created a new angular project with:
`$ tns create HelloWorld --template tns-template-blank-ng`

Now I can run tns preview.
