### ISSUE TITLE
Error: Cannot reattach ActivatedRouteSnapshot with a different number of children

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/nativescript-angular#1830]
Here is my routing:

```TS
const routes: Routes = [

    {
        path: "",
        redirectTo: "/tabs/default",
        pathMatch: "full"
    },
    {
        path: "tabs",
        loadChildren: "~/app/modules/tabs/tabs.module#TabsModule"
    },
    {
        path: "login",
        loadChildren: "~/app/modules/login/login.module#LoginModule"
    },
    {
        path: "register",
        loadChildren: "~/app/modules/register/register.module#RegisterModule"
    }

];
```

The scenario which leads to the error: First the app starts with tabs route, then I go to the login page, after that I go to register and then again I go to tabs page (and clean the history). After that if I go to login page again and get back to previous one (tabs page), the error occurs.

Any idea?

**Comment by vahidvdn** [comment]
@NickIliev @tsonevn Any idea on this?

**Comment by jocafi** [comment]
same problem here, but I am using Angular 8.0


```
  {
    path: ':mode',
    loadChildren: () => import('./challenge-edit/challenge-edit.module').then( mod => mod.ChallengeEditModule)
  },

```


```
 "dependencies": {
        "@angular/animations": "~8.0.0",
        "@angular/common": "~8.0.0",
        "@angular/compiler": "~8.0.0",
        "@angular/core": "~8.0.0",
        "@angular/forms": "~8.0.0",
        "@angular/http": "~8.0.0-beta.10",
        "@angular/platform-browser": "~8.0.0",
        "@angular/platform-browser-dynamic": "~8.0.0",
        "@angular/router": "~8.0.0",
        "nativescript-angular": "~8.0.0",
        "nativescript-theme-core": "~1.0.6",
        "nativescript-ui-sidedrawer": "^6.0.0",
        "reflect-metadata": "~0.1.13",
        "rxjs": "~6.5.2",
        "tns-core-modules": "^5.4.1",
        "zone.js": "~0.9.1"
    },

```


```
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot with a different number of children
JS: Error: Cannot reattach ActivatedRouteSnapshot with a different number of children
JS:     at setFutureSnapshotsOfActivatedRoutes (file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:78144:15) [angular]
JS:     at createNode (file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:78129:13) [angular]
JS:     at file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:78169:16 [angular]
JS:     at Array.map (<anonymous>) [angular]
JS:     at createOrReuseChildren (file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:78152:26) [angular]
JS:     at createNode (file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:78121:24) [angular]
JS:     at file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:78158:28 [angular]
JS:     at Array.map (<anonymous>) [angular]
JS:     at createOrReuseChildren (file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:78152:...


```

**Comment by vahidvdn** [comment]
@jocafi Yes, unfortunately, there is no feedback from anyone. Hope this will be fixed in new [Tab-View Redesign](https://github.com/NativeScript/NativeScript/issues/6967)

**Comment by lostation** [comment]
@vahidvdn Are you using <router-outlet> or <page-router-outlet> ?
It seems <page-router-outlet> handles correctly this issue and <router-outlet> not...unfortunately.

**Comment by vahidvdn** [comment]
@lostation No, page-router-outlet doesn't handle it correctly. See [here](https://github.com/NativeScript/login-tab-navigation-ng/blob/master/src/app/app.component.html).
Also see the issue at the [same repo](https://github.com/NativeScript/login-tab-navigation-ng/issues/7).

**Comment by lostation** [comment]
Ok maybe it’s not related to type of router outlet in your case.
Anyway, considering my issue, I’ve just replaced router outlet by page router outlet in my TabView’s children and the issue was gone.
It has to be linked somehow… I also wonder if this issue could be related to a clearHistory = true … I will give a try.
Sorry to be to not very useful …  I’m still discovering NativeScript…
Hope this bug will be fixed for TabView and its children’s routes of Nativescript v6 … wait and see.
L.

**Comment by bpaczkowski-merix** [comment]
I'm not sure if it will be helpful but in my case, the solution to this error was to use the additional parameter _skipLocationChange_ in options of _navigate_ method.

Eg.
```
navigateToHome() {
    const navigationOptions: any = {
      clearHistory: true,
      animated: false,
      skipLocationChange: true
    };

    return this.routerExtensions.navigate([''], navigationOptions);
  }
```

**Comment by mpilija** [comment]
Hi Guys,

Any news on this? Bot the same issue while navigating back:
this.routerExtensions.back();

**Comment by tskweres** [comment]
Same issue when using this.routerExtensions.back() with lazy-loaded tab routes

**Comment by phpdev90** [comment]
The same issue. Any idea?

**Comment by tskweres** [comment]
@bpaczkowski-merix  solution with skipLocationChange in the transition worked for me

**Comment by imerljak** [comment]
I'm having this issue without tab navigation on a lazy loaded module.
I'm using a single <page-router-outlet>.

It happens at random when I navigate back and forth from sibling routes of a lazy loaded module.
It seems that when I change pages too fast (activate the next route just when the view loads) something break and it stops any future navigation attempt.

I've tried @bpaczkowski-merix solution without success. Also tried navigating from nsRouterLink and the error persists.

If there's anything else that I can provide to clear up on this issue, please ask.

```
JS: ERROR Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot created from a different route
JS: Error: Cannot reattach ActivatedRouteSnapshot created from a different route
JS:     at setFutureSnapshotsOfActivatedRoutes (file:///node_modules/@angular/router/fesm5/router.js:1847:0) [angular]
JS:     at createNode (file:///node_modules/@angular/router/fesm5/router.js:1835:0) [angular]
JS:     at file:///node_modules/@angular/router/fesm5/router.js:1875:0 [angular]
JS:     at Array.map (<anonymous>) [angular]
JS:     at createOrReuseChildren (file:///node_modules/@angular/router/fesm5/router.js:1858:0) [angular]
JS:     at createNode (file:///node_modules/@angular/router/fesm5/router.js:1827:0) [angular]
JS:     at file:///node_modules/@angular/router/fesm5/router.js:1864:0 [angular]
JS:     at Array.map (<anonymous>) [angular]
JS:     at createOrReuseChildren (file:///data/data/br.com.dbsystem.apptra...
ERROR Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot created from a different route
Error: Cannot reattach ActivatedRouteSnapshot created from a different route
    at setFutureSnapshotsOfActivatedRoutes (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80712:15) [angular]
    at createNode (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80700:13) [angular]
    at file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80740:16 [angular]
    at Array.map (<anonymous>) [angular]
    at createOrReuseChildren (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80723:26) [angular]
    at createNode (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80692:24) [angular]
    at file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80729:28 [angular]
    at Array.map (<anonymous>) [angular]
    at createOrReuseChildren (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80723:26) [angular]
    at createNode (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80692:24) [angular]
    at createRouterState (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:80684:16) [angular]
    at MapSubscriber.project (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:82816:41) [angular]
    at MapSubscriber.push.../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:108527:35) [angular]
    at MapSubscriber.push.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (file:///data/data/br.com.dbsystem.apptransportadoras/files/app/vendor.js:103769:18) [angular]
```

**Comment by alqabali** [comment]
some issue here!

**Comment by mhmdhmd** [comment]
while navigating back use extra option in this.routerExtension.back()
use the following

`this.routerExtension.back({relativeTo: this.activatedRoute});`

i hope it handles correctly this issue

**Comment by prajilshresthaiw** [comment]
+1 for this issue.

**Comment by prajilshresthaiw** [comment]
> while navigating back use extra option in this.routerExtension.back()
> use the following
> 
> `this.routerExtension.back({relativeTo: this.activatedRoute});`
> 
> i hope it handles correctly this issue

This worked for me.

**Comment by PetroSuch** [comment]
Any idea about it ?

**Comment by PetroSuch** [comment]
Guys, what is the solve of the problem /

**Comment by PetroSuch** [comment]
i dont can use bottomnavigation inside my application, because i can go to component Tabs and but i can return back to him from different component
