### ISSUE TITLE
Barcode plugin in conflict with TextField when ListView is present

### ISSUE THREAD

**Issue by palpa** [NativeScript/nativescript-angular#189]
After scanning a bar code and try to enter some text in a TextField the app crashes with below exception (it can work the first time but fails after a second scan):
````
The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
com.tns.NativeScriptException: No weak reference found. Attempt to use cleared object reference id=2041
	at com.tns.Platform.getJavaObjectByID(Platform.java:637)
	at com.tns.Platform.callJSMethodNative(Native Method)
	at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
	at com.tns.Platform.callJSMethod(Platform.java:715)
	at com.tns.Platform.callJSMethod(Platform.java:694)
	at com.tns.Platform.callJSMethod(Platform.java:684)
	at com.tns.gen.android.text.TextWatcher_ftns_modules_ui_editable-text-base_editable-text-base_l22_c29__.afterTextChanged(android.text.TextWatcher.java)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:7994)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10040)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:970)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:497)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:679)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:279)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5433)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
````
I'm only able to reproduce the issue when a ListView is present in the same Page or in a previous Navigated one.

I've created a demo project here: https://github.com/palpa/ng-app

Please let me know if you need any other detail that helps to resolve issue.
Thanks!

**Comment by slavchev** [comment]
related to https://github.com/NativeScript/android-runtime/issues/382

**Comment by orsag** [comment]
Same crash happens when you start camera app, take a photo with takePicture function, then you go back to the same page from where you started your camera. And if on that page is a textfield and you tap it, it's gonna crash with error 'no weak reference...'. 

I tested this on 1.7.1 and also tried "master branch" 2.0.0. Compiled with 2.0 it will show nice popup "App crashed" as in native android app. On 1.7.1 it will show exception on the screen.
