### ISSUE TITLE
Cannot read property 'ContextCompat' of undefined

### ISSUE THREAD

**Issue by darkotacic** [NativeScript/nativescript-angular#1929]
**Environment**

 - CLI: 8.0.0
 - Cross-platform modules: 6.0.3
 - Android Runtime: 6.0.1
 - iOS Runtime: 6.0.1
 - NativeScript-Angular: 6.0.2
 - Angular: 8.0.0
 
**Describe the bug**
Recently I updated nativescript from version 5 to the recently released version 6. I had to remove a couple of deprecated modules from the project (Localhost). Afterwards I tried to do tns run command and I get this error in console:

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err: File: "file:///node_modules\nativescript-phone\index.js:6:0
System.err:
System.err: StackTrace:
System.err:     Frame: function:'../node_modules/nativescript-phone/index.js', file:'file:///node_modules\nativescript-phone\index.js:6:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./care/connect/connect-detail/connect-detail.component.ts', file:'file:///src\care\connect\connect-detail\connect-detail.component.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./care/care.module.ts', file:'file:///src\care\care.module.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./app.module.ts', file:'file:///src\app.module.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 1672, column: 69
System.err:     Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 1738, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src\webpack\bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src\webpack\bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err: File: "file:///node_modules\nativescript-phone\index.js:6:0
System.err:
System.err: StackTrace:
System.err:     Frame: function:'../node_modules/nativescript-phone/index.js', file:'file:///node_modules\nativescript-phone\index.js:6:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./care/connect/connect-detail/connect-detail.component.ts', file:'file:///src\care\connect\connect-detail\connect-detail.component.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./care/care.module.ts', file:'file:///src\care\care.module.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./app.module.ts', file:'file:///src\app.module.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 1672, column: 69
System.err:     Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 1738, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src\webpack\bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src\webpack\bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err: File: "file:///node_modules\nativescript-phone\index.js:6:0
System.err:
System.err: StackTrace:
System.err:     Frame: function:'../node_modules/nativescript-phone/index.js', file:'file:///node_modules\nativescript-phone\index.js:6:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./care/connect/connect-detail/connect-detail.component.ts', file:'file:///src\care\connect\connect-detail\connect-detail.component.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./care/care.module.ts', file:'file:///src\care\care.module.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'./app.module.ts', file:'file:///src\app.module.ts:1:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src\webpack\bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 1672, column: 69
System.err:     Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 1738, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src\webpack\bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src\webpack\bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src\webpack\bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.mypatientcare/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:663)
System.err:     at com.tns.Runtime.run(Runtime.java:655)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
System.err:     ... 8 more

I tried to delete the node_modules,hooks and platfroms folder and it did not work. I tired googled about this error and come up short. Any information could be helpfull.

**Comment by tsonevn** [comment]
Hi @darkotacic,
Try to clear up the project, by deleting `node_modules`, `platforms`, `hooks` folders and package-lock.json file and rebuild the project. If the issue persists, please provide more info about the problem(send us the full error log) and more info about your environment(CLI, `nativescript-angular`, `tns-core-modules`, `tns-android`, `tns-ios` versions). Also, it will help if you can send us the project or at least its package.json file.

**Comment by tsonevn** [comment]
closing due to inactivity
