### ISSUE TITLE
 StaticInjectorError(Platform: core)[HttpClient]

### ISSUE THREAD

**Issue by KhaledJNA** [NativeScript/nativescript-angular#1951]
{
  "nativescript": {
    "id": "org.nativescript.HttpBasics",
    "tns-android": {
      "version": "6.0.0"
    },
    "tns-ios": {
      "version": "6.0.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "nativescript-angular": "~8.0.0",
    "nativescript-theme-core": "~1.0.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "nativescript-dev-webpack": "~1.0.0",
    "typescript": "~3.4.0"
  },
  "gitHead": "f28dbc60d74dd2cef4b645afd8fdd63bbb12c73e",
  "readme": "NativeScript Application"
}

// >> http-get-service
import { Injectable } from "@angular/core";
import { HttpClient, HttpHeaders } from "@angular/common/http";

@Injectable(
     {
         providedIn: "root"
    }
)
export class HttpGetService{
  constructor(private http: HttpClient) { }
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
import { Component, OnInit } from "@angular/core";
import { HttpGetService } from "./services/http-get.service";
@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {

    constructor(private service : HttpGetService) {
        // Use the component constructor to inject providers.
    }

    ngOnInit(): void {
        // Init your component properties here.
    }
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptCommonModule } from "nativescript-angular/common";

import { HomeRoutingModule } from "./home-routing.module";
import { HomeComponent } from "./home.component";
import { NativeScriptHttpClientModule } from "nativescript-angular/http-client";

@NgModule({
    imports: [
        NativeScriptHttpClientModule,
        NativeScriptCommonModule,
        HomeRoutingModule
    ],
    declarations: [
        HomeComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class HomeModule { 

    constructor() { }

}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        AppRoutingModule
    ],
    declarations: [
        AppComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule { }

First test on Nativescript, i have this problem.  It 's not clear for me, i think my code is correct, but i have this message on console when i execute command tns preview :
StaticInjectorError(Platform: core)[HttpClient]: 
LOG from device  Khaled for the brave : NullInjectorError: No provider for HttpClient!
LOG from device  Khaled for the brave : ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[HttpClient]: 
LOG from device  Khaled for the brave : Error: NullInjectorError: No provider for HttpClient!
LOG from device  Khaled for the brave : at NullInjector.get (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bundles/core.umd.js:1310:21) [angular]
LOG from device  Khaled for the brave : at resolveToken (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bundles/core.umd.js:1548:22) [angular]
LOG from device  Khaled for the brave : at StaticInjector.get (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bundles/core.umd.js:1396:16) [angular]
LOG from device  Khaled for the brave : at tryResolveToken (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bundles/core.umd.js:1492:14) [angular]
LOG from device  Khaled for the brave : at resolveToken (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bundles/core.umd.js:1548:22) [angular]
LOG from device  Khaled for the brave : at tryResolveToken (file:///data/data/org.nativescript....

is this framework stable ??

**Comment by Pandishpan** [comment]
@KhaledJNA your imports are missing HttpClientModule from "@angular/common/http" 

import the HttpClientModule from "@angular/common/http"  in your AppModule

then add it to @NgModule.imports array

Check this SO thread for more info 
[https://stackoverflow.com/questions/47236963/no-provider-for-httpclient](https://stackoverflow.com/questions/47236963/no-provider-for-httpclient)
