### ISSUE TITLE
TestBed Integration broken

### ISSUE THREAD

**Issue by hypery2k** [NativeScript/nativescript-angular#2048]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules: 6.1.0
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.0
 - Plugin(s): - 
 - NativeScript-Angular: 8.2.0
 - Angular: 8.2.0
 
**Describe the bug**
Getting following error:

```
NativeScript / 12.0 (12.0; iPhone) Renderer E2E executes events inside NgZone when listen is called outside NgZone FAILED
	TypeError: null is not an object (evaluating 'this.platform.injector') in file:///app/vendor.js (line 69344)
	    at <Jasmine>
	at file:///app/vendor.js:82816:44
	    at <Jasmine>
	at file:///app/bundle.js:116:28
	    at <Jasmine>
```

**To Reproduce**
1. Create new project
2. Add test tools: `tns test init` && `npm i jasmine @types/jasmine --D`
3. Add test at `src/tests/example.ts`:
```
import { Component, ElementRef, NgZone, Renderer2 } from '@angular/core';
import { ComponentFixture, async } from '@angular/core/testing';
import { StackLayout } from 'tns-core-modules/ui/layouts/stack-layout';
import {
    nsTestBedAfterEach,
    nsTestBedBeforeEach,
    nsTestBedRender
} from 'nativescript-angular/testing';

@Component({
    template: `
        <StackLayout><Label text="Layout"></Label></StackLayout>
    `
})
export class ZonedRenderer {
    constructor(public elementRef: ElementRef, public renderer: Renderer2) {}
}

describe('Renderer E2E', () => {
    beforeEach(nsTestBedBeforeEach([ZonedRenderer]));
    afterEach(nsTestBedAfterEach(false));

    it('executes events inside NgZone when listen is called outside NgZone', async(() => {
        const eventName = 'someEvent';
        const view = new StackLayout();
        const eventArg = { eventName, object: view };
        const callback = arg => {
            expect(arg).toEqual(eventArg);
            expect(NgZone.isInAngularZone()).toBeTruthy();
        };
        nsTestBedRender(ZonedRenderer).then(
            (fixture: ComponentFixture<ZonedRenderer>) => {
                fixture.ngZone.runOutsideAngular(() => {
                    fixture.componentInstance.renderer.listen(
                        view,
                        eventName,
                        callback
                    );

                    view.notify(eventArg);
                });
            }
        );
    }));
});

```
4.

**Expected behavior**
test works ;)

**Sample project**
https://github.com/hypery2k/tns_bug_2048

Just checkout and run `tns test ios`

**Additional context**
-

**Comment by hypery2k** [comment]
sorry, can be ignored. Setup issue on my side: You'll find a sample here: https://github.com/hypery2k/tns_testbed_sample
