### ISSUE TITLE
platform_browser_1.ɵsetRootDomAdapter is not a function

### ISSUE THREAD

**Issue by sdrissen** [NativeScript/nativescript-angular#2093]
**Environment**
 - CLI: 
```
tns info
√ Getting NativeScript components versions information...
√ Component nativescript has 6.2.2 version and is up to date.
√ Component tns-core-modules has 6.2.3 version and is up to date.
√ Component tns-android has 6.2.0 version and is up to date.
× Component tns-ios is not installed.
```
 - Angular: 9.0.0-rc.4
 - compiled for Android
 
**Describe the bug**
On android runtime, there is this error `platform_browser_1.ɵsetRootDomAdapter is not a function`.
What does it mean?
Could it be possible, that there is a function `rɵsetRootDomAdapter`?
I have no clue, what could go wrong. There is not a single google result.

**To Reproduce**
I don't know.

**Expected behavior**
No Error on runtime.

**Sample project**
I migrated an existing Angular Project to NativeScript with `ng add @nativescript/schematics`.
I considered to smaller it, until it works. But I don't know where to start.

**Additional context**
```
An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
TypeError: platform_browser_1.ɵsetRootDomAdapter is not a function
File: (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77298:27)

StackTrace: 
push.../node_modules/@nativescript/angular/dom-adapter.js.NativeScriptDomAdapter.makeCurrent(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77298:28)
	at ../node_modules/@nativescript/angular/dom-adapter.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77439:24)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77757:1)
	at ../node_modules/@nativescript/angular/platform-common.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78070:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78150:25)
	at ../node_modules/@nativescript/angular/platform.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78193:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at ../node_modules/nativescript-angular/platform.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:120383:10)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:214:87)
	at ./main.tns.ts(file:///data/data/org.nativescript.ngsample/files/app/bundle.js:286:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at checkDeferredModules(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:31:19)
	at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:2:57)
	at require(:1:266)


TypeError: platform_browser_1.ɵsetRootDomAdapter is not a function

StackTrace:
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
TypeError: platform_browser_1.ɵsetRootDomAdapter is not a function
File: (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77298:27)

StackTrace: 
push.../node_modules/@nativescript/angular/dom-adapter.js.NativeScriptDomAdapter.makeCurrent(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77298:28)
	at ../node_modules/@nativescript/angular/dom-adapter.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77439:24)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77757:1)
	at ../node_modules/@nativescript/angular/platform-common.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78070:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78150:25)
	at ../node_modules/@nativescript/angular/platform.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78193:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at ../node_modules/nativescript-angular/platform.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:120383:10)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:214:87)
	at ./main.tns.ts(file:///data/data/org.nativescript.ngsample/files/app/bundle.js:286:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at checkDeferredModules(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:31:19)
	at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:2:57)
	at require(:1:266)


TypeError: platform_browser_1.ɵsetRootDomAdapter is not a function
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6163)
	at android.app.ActivityThread.access$1200(ActivityThread.java:235)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: com.tns.NativeScriptException: Error calling module function 
TypeError: platform_browser_1.ɵsetRootDomAdapter is not a function
File: (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77298:27)

StackTrace: 
push.../node_modules/@nativescript/angular/dom-adapter.js.NativeScriptDomAdapter.makeCurrent(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77298:28)
	at ../node_modules/@nativescript/angular/dom-adapter.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77439:24)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:77757:1)
	at ../node_modules/@nativescript/angular/platform-common.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78070:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78150:25)
	at ../node_modules/@nativescript/angular/platform.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:78193:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at ../node_modules/nativescript-angular/platform.js(file:///data/data/org.nativescript.ngsample/files/app/vendor.js:120383:10)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at fn(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:214:87)
	at ./main.tns.ts(file:///data/data/org.nativescript.ngsample/files/app/bundle.js:286:30)
	at __webpack_require__(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:754:30)
	at checkDeferredModules(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/org.nativescript.ngsample/files/app/runtime.js:31:19)
	at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:2:57)
	at require(:1:266)


TypeError: platform_browser_1.ɵsetRootDomAdapter is not a function
	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:674)
	at com.tns.Runtime.run(Runtime.java:666)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6158)
	... 8 more
```

**Comment by NickIliev** [comment]
@sdrissen Angular: 9.0.0-rc.4 is not supported by NativeScript and `nativescript-angular`

**Comment by MattRiddell** [comment]
Same problem with Angular 9 normal which is the default Angular now

**Comment by MattRiddell** [comment]
Ok cool after actually RTFM I can confirm it is working with the following steps:

```bash
npm i nativescript-angular@ivy  
./node_modules/.bin/update-app-ng-deps
npm i
```
