### ISSUE TITLE
Cannot read property 'ContextCompat' of undefined on Android

### ISSUE THREAD

**Issue by Reynk** [NativeScript/nativescript-angular#2107]
**Environment:**
- CLI: 8.0.0
- NativeScript-Angular: 8.0.2
- Angular: 8.0.0
- tns --version: 6.3.2
- tns-core-modules: "~6.0.0"
- nativescript-angular: "8.0.2"
- tns-ios: 6.0.2"
- tns-android: "6.3.1"
    

```System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err: File: (file:///node_modules\nativescript-phone\index.js:6:0)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/nativescript-phone/index.js(file:///node_modules\nativescript-phone\index.js:6:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./services/communication.service.ts(file:///app\services\communication.service.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./services/services.module.ts(file:///app\services\services.module.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./app.module.ts(file:///app\app.module.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/be.advani.DPlan/files/app/bundle.js:372:69)
System.err:     at ./main.ts(file:///data/data/be.advani.DPlan/files/app/bundle.js:440:30)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file:///app\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///app\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/be.advani.DPlan/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err:
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err: File: (file:///node_modules\nativescript-phone\index.js:6:0)
System.err:
System.err: StackTrace: 
System.err: ../node_modules/nativescript-phone/index.js(file:///node_modules\nativescript-phone\index.js:6:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./services/communication.service.ts(file:///app\services\communication.service.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./services/services.module.ts(file:///app\services\services.module.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./app.module.ts(file:///app\app.module.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/be.advani.DPlan/files/app/bundle.js:372:69)
System.err:     at ./main.ts(file:///data/data/be.advani.DPlan/files/app/bundle.js:440:30)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file:///app\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///app\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/be.advani.DPlan/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5954)
System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:200)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:201)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6810)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err: File: (file:///node_modules\nativescript-phone\index.js:6:0)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/nativescript-phone/index.js(file:///node_modules\nativescript-phone\index.js:6:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./services/communication.service.ts(file:///app\services\communication.service.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./services/services.module.ts(file:///app\services\services.module.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at ./app.module.ts(file:///app\app.module.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at fn(file:///app\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/be.advani.DPlan/files/app/bundle.js:372:69)
System.err:     at ./main.ts(file:///data/data/be.advani.DPlan/files/app/bundle.js:440:30)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file:///app\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///app\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/be.advani.DPlan/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Cannot read property 'ContextCompat' of undefined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5949)
System.err:     ... 8 more
```

On iOS it seems to run just fine

[My issue seems to be similar to this one](https://github.com/NativeScript/nativescript-angular/issues/1929)

But as you can see the author has not answered with any more info and I have already tried what was mentioned in the thread as well as what others suggested to do but with no luck... Any help?

My package.json file

{
  "description": "mobile application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "secret",
    "tns-ios": {
      "version": "6.0.2"
    },
    "tns-android": {
      "version": "6.3.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "8.0.0",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/router": "8.0.0",
    "nativescript-angular": "8.0.2",
    "nativescript-email": "^1.5.3",
    "nativescript-geolocation": "^5.0.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-local-notifications": "^3.1.0",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-phone": "1.3.1",
    "nativescript-plugin-firebase": "^10.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toasty": "^2.0.1",
    "nativescript-ui-calendar": "5.0.0",
    "nativescript-ui-listview": "^7.1.0",
    "nativescript-ui-sidedrawer": "7.0.0",
    "nativescript-zip": "^4.0.2",
    "reflect-metadata": "~0.1.10",
    "rxjs": "6.3.3",
    "tns-core-modules": "~6.0.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.800.3",
    "@angular/compiler-cli": "8.0.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "~1.1.0",
    "tslint": "~5.10.0",
    "typescript": "3.4.5",
    "tns-platform-declarations": "6.0.1"
  }
}

**Comment by Reynk** [comment]
I solved the problem by 
`npm i nativescript-phone@latest`
