### ISSUE TITLE
Unit Testing - ZoneAwareError when running unit tests

### ISSUE THREAD

**Issue by aubrey-fowler** [NativeScript/nativescript-angular#2133]
I'm writing an app with NativeScript 6+ and Angular 8+. I'm trying to write some unit tests and get them up and running. 

I have read the documentation on unit testing: https://docs.nativescript.org/tooling/testing/testing 

I ran **tns test init** and **tns test android** to prepare my tests. I followed the directions there for setting up the tests and using TestBed. My tests are not working and throwing errors. Here is my repository: https://github.com/aubrey-fowler/NativeScriptUnitTests

sample test:

```
import { ItemsComponent } from '../app/item/items.component';
import { ItemService } from '../app/item/item.service';

import { nsTestBedAfterEach, nsTestBedBeforeEach, nsTestBedRender } from 'nativescript-angular/testing';

describe('ItemsComponent Test', () => {

    beforeEach(nsTestBedBeforeEach([ItemService, ItemsComponent]));
    afterEach(nsTestBedAfterEach(false));

    it('should be defined', () => {

        nsTestBedRender(ItemsComponent).then((fixture) => {
            fixture.detectChanges();
            const component = fixture.componentInstance;
            expect(component).toBeTruthy();
        });

    });

});
```

When I run my tests, I'm getting this error:

```
NativeScript / 29 (10; SM-G960F) ItemsComponent Test should be defined FAILED
        error properties: Object({ originalStack: 'Error: Can't resolve all parameters for ApplicationModule: (?).
            at ZoneAwareError (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:85903:33)
            at syntaxError (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:9475:17)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28631:35)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28523:26)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28391:24)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/com ...
        Error: Can't resolve all parameters for ApplicationModule: (?).
            at ZoneAwareError (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:85903:33)
            at syntaxError (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:9475:17)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28631:35)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28523:26)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28391:24)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28201:35)
            at file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28288:55
            at <Jasmine>
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28266:49)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28201:35)
            at file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28288:55
            at <Jasmine>
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28266:49)
            at JitCompiler.push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:34433:51)
            at JitCompiler.push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndAllComponents (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:34421:36)
        error properties: Object({ originalStack: 'Error: Can't resolve all parameters for ApplicationModule: (?).
            at ZoneAwareError (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:85903:33)
            at syntaxError (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:9475:17)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28631:35)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28523:26)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28391:24)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/com ...
        Error: Can't resolve all parameters for ApplicationModule: (?).
            at ZoneAwareError (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:85903:33)
            at syntaxError (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:9475:17)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28631:35)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28523:26)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28391:24)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28201:35)
            at file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28288:55
            at <Jasmine>
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28266:49)
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28201:35)
            at file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28288:55
            at <Jasmine>
            at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:28266:49)
            at JitCompiler.push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:34433:51)
            at JitCompiler.push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndAllComponents (file:///data/data/org.nativescript.UnitTesting/files/app/vendor.js:34421:36
```

**Comment by mahmoudajawad** [comment]
@aubrey-fowler, change your `beforeEach` to:
```typescript
beforeEach(nsTestBedBeforeEach([ItemsComponent], [ItemService,]));
```
This doesn't seem to be documented, but if you hover `nsTestBedBeforeEach` it will give the following nice explanations on how to setup `TestBed` for your tests:
```
(alias) nsTestBedBeforeEach(components: any[], providers?: any[], imports?: any[], entryComponents?: any[]): (done: any) => void
import nsTestBedBeforeEach
Helper for configuring a TestBed instance for rendering components for test. Ideally this would not be needed, and in truth it's just a wrapper to eliminate some boilerplate. It exists because when you need to specify entryComponents for a test the setup becomes quite a bit more complex than if you're just doing a basic component test.

More about entryComponents complexity: https://github.com/angular/angular/issues/12079

Use:
   beforeEach(nsTestBedBeforeEach([MyComponent,MyFailComponent]));
NOTE* Remember to pair with {@see nsTestBedAfterEach}

@param components — Any components that you will create during the test
@param providers — Any services your tests depend on
@param imports — Any module imports your tests depend on
@param entryComponents — Any entry components that your tests depend on
```

So, components and services (Injectables) don't come under one single Array, but rather separated. You can pass a third one for your module imports as well.
