### ISSUE TITLE
App crash whe using useCache="true" Image tag property on tns run android with Android 6+ 

### ISSUE THREAD

**Issue by ofe2358** [NativeScript/nativescript-angular#2140]
**Environment**
 - CLI:  "6.3.1"
 - Android Runtime: from Android 6 and any higher versions
 - NativeScript-Angular: "~8.20.0",
 - Angular:"~8.2.0",

**Describe the bug**
Using useCache property on Image tag like this (only on Android v6++)

` <Image useCache="true"  src="~/image.png"></Image>`

and runing for development (tns run android) app crash with this trace log:

> System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: JNI Exception occurred (SIGABRT).
System.err: =======
System.err: Check the 'adb logcat' for additional information about the error.
System.err: =======
System.err: StackTrace:
System.err: push.../node_modules/@nativescript/core/ui/image/image.js.Image._createImageSourceFromSrc(file:///node_modules/@nativescript/core/ui/image/image.js:103:0)
System.err:     at push.../node_modules/@nativescript/core/ui/image/image.js.Image.<computed>(file:///node_modules/@nativescript/core/ui/image/image.js:167:0)
System.err:     at applyAllNativeSetters(file:///node_modules/@nativescript/core/ui/core/properties/properties.js:1046:0)
System.err:     at initNativeView(file:///node_modules/@nativescript/core/ui/core/properties/properties.js:990:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onResumeNativeUpdates(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:628:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._resumeNativeUpdates(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:273:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:232:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/content-view/content-view.js.ContentView.eachChildView(file:///node_modules/@nativescript/core/ui/content-view/content-view.js:70:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at push.../node_modules/@nativescript/core/ui/scroll-view/scroll-view-common.js.ScrollViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/scroll-view/scroll-view-common.js:31:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/content-view/content-view.js.ContentView.eachChildView(file:///node_modules/@nativescript/core/ui/content-view/content-view.js:70:0)
System.err:     at push.../node_modules/@nativescript/core/ui/page/page-common.js.PageBase.eachChildView(file:///node_modules/@nativescript/core/ui/page/page-common.js:126:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at push.../node_modules/@nativescript/core/ui/page/page.js.Page.onLoaded(file:///node_modules/@nativescript/core/ui/page/page.js:43:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addViewCore(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:435:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:421:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView(file:///node_modules/@nativescript/core/ui/frame/frame.js:700:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/fragment.js.FragmentClass.onCreateView(file:///node_modules/@nativescript/core/ui/frame/fragment.js:29:0)

**It does not happen on lower Android versions, or when realease build APK**

**To Reproduce**
With an app with any html like this
` <Image useCache="true"  src="~/image.png"></Image>`
on Android 6+ when tns run android

**Comment by NickIliev** [comment]
Reproducible with Core TypeScript application as well. Demo app [here](https://github.com/NickIliev/NS-Issues-2020/tree/master/nativescript-angular/issue-2140-tsc).

Steps to reproduce: just run the demo app and it will crash due to [this line](https://github.com/NickIliev/NS-Issues-2020/blob/master/nativescript-angular/issue-2140-tsc/app/main-page.xml#L5)

Crashes with
```
JNI DETECTED ERROR IN APPLICATION: unexpected jboolean value: 129
```

ADB Logcat
```
2020-04-06 15:08:18.449 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: unexpected jboolean value: 129
2020-04-06 15:08:18.449 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]     in call to CallVoidMethodA
2020-04-06 15:08:18.449 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]     from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
2020-04-06 15:08:18.449 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542] "main" prio=5 tid=1 Runnable
2020-04-06 15:08:18.449 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x7544ba48 self=0x776d34214c00
2020-04-06 15:08:18.449 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   | sysTid=18357 nice=-10 cgrp=default sched=0/0 handle=0x776db9965548
2020-04-06 15:08:18.449 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   | state=R schedstat=( 1922977023 333978995 927 ) utm=143 stm=49 core=0 HZ=100
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   | stack=0x7ffe23e35000-0x7ffe23e37000 stackSize=8MB
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   | held mutexes= "mutator lock"(shared held)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #00 pc 0000000000403e33  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+227)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #01 pc 00000000004ee1f7  /system/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+343)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #02 pc 000000000031da53  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1011)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #03 pc 000000000031de52  /system/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, __va_list_tag*)+82)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #04 pc 00000000000fce67  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+183)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #05 pc 00000000000fcb2a  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckNonHeapValue(char, art::(anonymous namespace)::JniValueType)+682)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #06 pc 00000000000fb335  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+165)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #07 pc 00000000000fb5a4  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+788)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #08 pc 00000000000fa9b6  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+758)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #09 pc 00000000001003c0  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CheckCallArgs(art::ScopedObjectAccess&, art::(anonymous namespace)::ScopedCheck&, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, art::InvokeType, art::(anonymous namespace)::VarArgs const*)+160)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #10 pc 000000000010103c  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodA(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, art::Primitive::Type, art::InvokeType)+940)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #11 pc 00000000000ed974  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallVoidMethodA(_JNIEnv*, _jobject*, _jmethodID*, jvalue*)+36)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #12 pc 000000000027bbf9  /data/app/org.nativescript.issue2140tsc-FCjTdHXr4srQO6Q92RTY7g==/lib/x86_64/libNativeScript.so (???)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #13 pc 000000000026fb79  /data/app/org.nativescript.issue2140tsc-FCjTdHXr4srQO6Q92RTY7g==/lib/x86_64/libNativeScript.so (???)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #14 pc 0000000000290eb7  /data/app/org.nativescript.issue2140tsc-FCjTdHXr4srQO6Q92RTY7g==/lib/x86_64/libNativeScript.so (???)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   native: #15 pc 0000000000a4da23  /data/app/org.nativescript.issue2140tsc-FCjTdHXr4srQO6Q92RTY7g==/lib/x86_64/libNativeScript.so (???)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethodNative(Native method)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethod(Runtime.java:1160)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethod(Runtime.java:1138)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethod(Runtime.java:1134)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at android.os.Handler.handleCallback(Handler.java:873)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at android.os.Handler.dispatchMessage(Handler.java:99)
2020-04-06 15:08:18.450 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at android.os.Looper.loop(Looper.java:193)
2020-04-06 15:08:18.451 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at android.app.ActivityThread.main(ActivityThread.java:6669)
2020-04-06 15:08:18.451 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at java.lang.reflect.Method.invoke(Native method)
2020-04-06 15:08:18.451 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2020-04-06 15:08:18.451 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-04-06 15:08:18.451 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: java_vm_ext.cc:542] 
2020-04-06 15:08:18.526 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: runtime.cc:558] Runtime aborting...
2020-04-06 15:08:18.527 18357-18357/org.nativescript.issue2140tsc A/pt.issue2140ts: runtime.cc:558] Dumping all threads without appropriate locks held: thread list lock mutator lock

```
