### ISSUE TITLE
tns run failed after migrate to Nativescript 6

### ISSUE THREAD

**Issue by albert0106** [NativeScript/nativescript-angular#2148]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.0
 - Cross-platform modules: 6.5.1
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
 - Plugin(s): 
 - NativeScript-Angular: 8.21.0
 - Angular: 8.2.0
 
**Describe the bug**

when` tns run android --bundle` system error and i don't know to solved this.

```
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'readText' of undefined
JS: TypeError: Cannot read property 'readText' of undefined
JS:     at file: node_modules\@nativescript\core\file-system\file-system-access.android.js:249:0
JS:     at new ZoneAwarePromise (file: node_modules\@nativescript\angular\zone-js\dist\zone-nativescript.js:902:0)
JS:     at FileSystemAccess.push.../node_modules/@nativescript/core/file-system/file-system-access.js.FileSystemAccess.readTextAsync (file: node_modules\@nativescript\core\file-system\file-system-access.android.js:247:0)
JS:     at file: node_modules\@nativescript\core\file-system\file-system.js:277:0
JS:     at new ZoneAwarePromise (file: node_modules\@nativescript\angular\zone-js\dist\zone-nativescript.js:902:0)
JS:     at File.push.../node_modules/@nativescript/core/file-system/file-system.js.File.readText (file: node_modules\@nativescript\core\file-system\file-system.js:268:0)
JS:     at file: node_modules\nativescript-ngx-fonticon\services\fonticon.service.js:48:0
JS:     at new ZoneAwarePromise (file:///data/data/co.id.fasapay.mobile/files/app/vendor.js:9322...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onViewAttachedToWindow failed
System.err: TypeError: Cannot read property 'extend' of undefined
System.err:
System.err: StackTrace:
System.err: __extends(/data/data/co.id.fasapay.mobile/files/internal/ts_helpers.js:51:36)
System.err:     at (file: node_modules\@nativescript\core\ui\frame\fragment.android.js:4:0)
System.err:     at (file: node_modules\@nativescript\core\ui\frame\fragment.android.js:54:1)
System.err:     at ../node_modules/@nativescript/core/ui/frame/fragment.js(file:///data/data/co.id.fasapay.mobile/files/app/vendor.js:115700:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ensureFragmentClass(file: node_modules\@nativescript\core\ui\frame\frame.android.js:624:4)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.Frame.createFragment(file: node_modules\@nativescript\core\ui\frame\frame.android.js:209:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.Frame._navigateCore(file: node_modules\@nativescript\core\ui\frame\frame.android.js:303:0)System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame-common.js.FrameBase.performNavigation(file: node_modules\@nativescript\core\ui\frame\frame-common.js:300:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame-common.js.FrameBase._processNextNavigationEntry(file: node_modules\@nativescript\core\ui\frame\frame-common.js:291:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.Frame._processNextNavigationEntry(file: node_modules\@nativescript\core\ui\frame\frame.android.js:160:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.Frame._onAttachedToWindow(file: node_modules\@nativescript\core\ui\frame\frame.android.js:128:0)
System.err:     at AttachListener.onViewAttachedToWindow(file: node_modules\@nativescript\core\ui\frame\frame.android.js:39:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.gen.java.lang.Object_vendor_116994_36_AttachListener.onViewAttachedToWindow(Object_vendor_116994_36_AttachListener.java:18)
System.err:     at android.view.View.dispatchAttachedToWindow(View.java:18382)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3399)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3406)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3406)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1834)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1532)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7419)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:888)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:819)
System.err:     at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:991)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:201)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6810)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**To Reproduce**

**Expected behavior**
can run application

**Sample project**

i use on sample code in market.nativescript : https://play.nativescript.org/?template=play-ng&id=Hqp5UQ&v=6155

**Additional context**

**Comment by NickIliev** [comment]
The linked Playground is migrated to NativeScript 6.5 and is working as expected - can you clarify if there are additional steps that I need to execute in order to reproduce the issue?

**Comment by albert0106** [comment]
> The linked Playground is migrated to NativeScript 6.5 and is working as expected - can you clarify if there are additional steps that I need to execute in order to reproduce the issue?
> 
> Note: you don't need to add `--bundle` to run a Webpack build as from some time all NativeScript projects are built with Webpack by default.

I have a problem before migrate to 6.5 . The problem is when i use unit-testing with karma or anything else. When i code unit-testing (example : when click button and output a message) and run test, this code works but there is no message  output that i code, just Success 0 of 0.
Then i migrate because i hope this code can run and testing in nativescript 6.5 . After i run the instruction on https://docs.nativescript.org/releases/upgrade-instructions step by step, and then `tns run android` i have an error like that.

**Comment by albert0106** [comment]
I found a solution

-  create new project and copy source code to the lastest nativescript version
