### ISSUE TITLE
Error: Invalid rule result: Instance of class Promise.

### ISSUE THREAD

**Issue by BingeCode** [NativeScript/nativescript-angular#2160]
I am getting this error upon completing the [Creating a New Project](https://docs.nativescript.org/angular/code-sharing/creating-a-new-project) guide in the docs. 
The app builds just fine, but generating Angular/NS components via the NS CLI with `tns generate component some-component` throws following error:

```
Error: Invalid rule result: Instance of class Promise.
    at t.project (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:250:1038)
    at t._tryNext (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:30:1878)
    at t._next (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:30:1780)
    at t.next (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1093)
    at e._subscribe (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:74:13873)
    at e._trySubscribe (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:4641)
    at e.subscribe (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:4427)
    at e.call (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:30:1459)
    at e.subscribe (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:4299)
    at C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:145:10377
    at s (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:6063)
    at t._innerSub (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:30:2033)
    at t._tryNext (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:30:1957)
    at t._next (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:30:1780)
    at t.next (C:\Users\BenediktScheffbuch\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1093)
    at SafeSubscriber.__tryOrUnsub (C:\Users\BenediktScheffbuch\source\dsp-IT\test\mobileApp\node_modules\rxjs\internal\Subscriber.js:207:16)
```

I've tried the instructions in one [stackoverflow thread](https://stackoverflow.com/questions/56647865/invalid-rule-result-instance-of-class-promise) and an issue created in this [issue council](https://github.com/angular/angular-cli/issues/15290), that was never solved.

I even deleted my global `node_modules` before doing the Creating a New Project guide and reinstalled the latest Angular CLI, NativeScript CLI and NativeScript schematics.

The curiosity is, that we have an existing Angular project that we integrated with NativeScript, where everything worked like a charm. But we cannot find the difference in between both project setups that is causing this error for us.

**Comment by SergeyMell** [comment]
Same issue for me

**Comment by jsoft88** [comment]
Anyone managed to solve this or find a workaround at least?

**Comment by KeithMarex** [comment]
Same issue on my end

**Comment by borthakuraj** [comment]
Same issue for me. Has anyone managed to workaround it?
