### ISSUE TITLE
Observable and applicationOn are emitting too many times on app.component.ts

### ISSUE THREAD

**Issue by Arystosedes** [NativeScript/nativescript-angular#2162]
**Describe the bug**
Hi, I have a very weird bug (?) in my test app. When user login (it's only a mock but shows enough the problem),  then move that app to the background (home button on my device), then back to the app and repeat that steps few times, then if the user clicks logout button, the subscription will emit as many times as I moved the app to the background and back before. 

So if I move app to the background and open that app 5 times, then authState emits 5 times in console.logs

It's simple code.

app.component.ts
```
import { Component, OnInit } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { ApplicationEventData, on as applicationOn, suspendEvent } from 'tns-core-modules/application';

const user$ = new BehaviorSubject(null);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  isLoggedIn: any;

  constructor() {
    console.log('constructor');
    applicationOn(suspendEvent, (args: ApplicationEventData) => {
      console.log('AppComponent suspendEvsent');
    });
  }

  get authState(): Observable<any> {
    return user$.asObservable();
  }

  ngOnInit() {
    this.isLoggedIn = this.authState;
    this.authState.subscribe((user) => {
      console.log('authState', !!user);
    });
  }

  login() {
    user$.next({ isloggedIn: true, name: 'Gienek' });
  }

  logout() {
    user$.next(null);
  }
}
```
app.component.html
```
<StackLayout class="p-20">
  <button *ngIf="isLoggedIn | async else logoutBtn" text="Logout" (tap)="logout()"></button>
  <ng-template #logoutBtn>
    <button text="Login" (tap)="login()"></button>
  </ng-template>
</StackLayout>
```
```
import { platformNativeScriptDynamic } from 'nativescript-angular/platform';

import { AppModule } from '@src/app/app.module';

// A traditional NativeScript application starts by initializing global objects,
// setting up global CSS rules, creating, and navigating to the main page.
// Angular applications need to take care of their own initialization: modules, components, directives, routes, DI providers.
// A NativeScript Angular app needs to make both paradigms work together,
// so we provide a wrapper platform object, platformNativeScriptDynamic,
// that sets up a NativeScript application and can bootstrap the Angular framework.
platformNativeScriptDynamic().bootstrapModule(AppModule);
```
Another thing is console.log in suspendEvent. It is emitting also the wrong number of times (the same suspendEvent code in main.tns.ts is emitting only once, what is correct).

The weird thing is if I try to repeat this on https://play.nativescript.org/?template=play-ng&id=eXX8RG&v=2 it's working properly! Absolutely the same code! What is happening? Something wrong with angular.json? The problem occurs in android emulator and a real device.

**Environment**
```
{
  "name": "test",
  "nativescript": {
    "id": "org.nativescript.voclicktest",
    "tns-android": {
      "version": "6.4.1"
    }
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android",
    "ios": "tns run ios",
    "mobile": "tns run",
    "preview": "tns preview"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.1",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "core-js": "^2.5.4",
    "nativescript-angular": "~8.0.1",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.5",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.5",
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@nativescript/schematics": "~0.7.0",
    "@nativescript/tslint-rules": "~0.0.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nativescript-dev-webpack": "~1.0.0",
    "node-sass": "^4.7.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "webpack-cli": "^3.0.2"
  }
}

```

**Comment by abhayastudios** [comment]
@Arystosedes did you ever find the cause for this? I have the same situation wherever I define some application resume event, on Android (iOS works fine) the `doSomething()` will be executed for the number of times that I suspend and resume the app.

```
ngOnInit() {
  applicationOn(resumeEvent, (args: ApplicationEventData) => {
    doSomething()
  });
}
```

**Comment by NathanaelA** [comment]
1. Is this in a app that you are currently developing and using HMR?    I have seen where when I make a change to my code the HMR can cause the events to be re-registered.    

2. In addition, you could also add a console log to the ngOnInt() to see if it is getting called multiple times as it will add a new resume event each time it executes...

**Comment by abhayastudios** [comment]
@NathanaelA 

1. Indeed an app that still runs on NS 6.5

```
$ tns info
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.5.1 and the latest available version is 7.0.8.
⚠ Update available for component @nativescript/core. Your current version is 6.5.20 and the latest available version is 7.0.9.
✔ Component tns-android has 6.5.3 version and is up to date.
✔ Component tns-ios has 6.5.2 version and is up to date.
```

Regarding HMR I actually disable HMR to avoid all kind of things, so I just run:

```
$ tns run android --no-hmr
```

2. Yes I have that in my code, for example I have two places where I listen to resume events and then I will see console log output like (in this case I would have suspended/resumed the app 4 times:

```
JS: ChatProvider resumeEvent: updating chats...
JS: ChatProvider resumeEvent: updating chats...
JS: ChatProvider resumeEvent: updating chats...
JS: ChatProvider resumeEvent: updating chats...
JS: checkAndroidUpdate: onFailure
JS: checkStoreUpdate: Install Error(-6): The download/install is not allowed, due to the current device state (e.g. low battery, low disk space, ...). (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_INSTALL_NOT_ALLOWED)
JS: checkAndroidUpdate: onFailure
JS: checkStoreUpdate: Install Error(-6): The download/install is not allowed, due to the current device state (e.g. low battery, low disk space, ...). (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_INSTALL_NOT_ALLOWED)
JS: checkAndroidUpdate: onFailure
JS: checkStoreUpdate: Install Error(-6): The download/install is not allowed, due to the current device state (e.g. low battery, low disk space, ...). (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_INSTALL_NOT_ALLOWED)
JS: checkAndroidUpdate: onFailure
JS: checkStoreUpdate: Install Error(-6): The download/install is not allowed, due to the current device state (e.g. low battery, low disk space, ...). (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_INSTALL_NOT_ALLOWED)
```

**Comment by NathanaelA** [comment]
> So I just added a console log to the ngOnInit of the AppComponent and indeed on Android every time I suspend/resume the app binds again (but not on iOS). I mean I could use a flag to ensure that the binding happens only once, but since iOS doesn't behave like that shouldn't Android be consistent with that?

So something is calling the ngOnInit again.   Their could be any number of reasons this is occurring.   Some phones will swap out the app and then page it back in on resume. 

One thing you can do is do is add a `console.log((new Error()).stack);` to the ngOnInit and see what the call stack is when it resumes to try and figure out why ngOnInit is being called on every resume...

**Comment by abhayastudios** [comment]
@NathanaelA First off thanks for your help! 

I assumed this is just an Android vs iOS thing because it happens on two real Android devices and the simulator as well. Seems like the stack is identical on both launch and resume and that also on resume it is running `ApplicationRef.bootstap` (I would assume this should not run on resume).

This is the stack on app launch:
```
Error
    at new ZoneAwareError (file:///data/data/tech.mokum.shine/files/app/vendor.js:91745:33)
    at AppComponent.module.exports.push../app/app.component.ts.AppComponent.ngOnInit (file:///data/data/tech.mokum.shine/files/app/bundle.js:640:22)
    at checkAndUpdateDirectiveInline (file:///data/data/tech.mokum.shine/files/app/vendor.js:59205:19)
    at checkAndUpdateNodeInline (file:///data/data/tech.mokum.shine/files/app/vendor.js:67603:20)
    at checkAndUpdateNode (file:///data/data/tech.mokum.shine/files/app/vendor.js:67565:16)
    at prodCheckAndUpdateNode (file:///data/data/tech.mokum.shine/files/app/vendor.js:68106:5)
    at Object.eval [as updateDirectives] (ng:///AppModule/AppComponent_Host.ngfactory.js:12:9)
    at Object.updateDirectives (file:///data/data/tech.mokum.shine/files/app/vendor.js:67894:72)
    at Object.checkAndUpdateView (file:///data/data/tech.mokum.shine/files/app/vendor.js:67547:14)
    at ViewRef_.push.../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges (file:///data/data/tech.mokum.shine/files/app/vendor.js:58794:22)
    at ApplicationRef.push.../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick (file:///data/data/tech.mokum.shine/files/app/vendor.js:65217:26)
    at ApplicationRef.push.../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent (file:///data/data/tech.mokum.shine/files/app/vendor.js:65272:14)
    at ApplicationRef.push.../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap (file:///data/data/tech.mokum.shine/files/app/vendor.js:65189:14)
    at file:///data/data/tech.mokum.shine/files/app/vendor.js:64904:81
    at Array.forEach (<anonymous>)
```

This is the stack on app resume:
```
Error
    at new ZoneAwareError (file:///data/data/tech.mokum.shine/files/app/vendor.js:91745:33)
    at AppComponent.module.exports.push../app/app.component.ts.AppComponent.ngOnInit (file:///data/data/tech.mokum.shine/files/app/bundle.js:640:22)
    at checkAndUpdateDirectiveInline (file:///data/data/tech.mokum.shine/files/app/vendor.js:59205:19)
    at checkAndUpdateNodeInline (file:///data/data/tech.mokum.shine/files/app/vendor.js:67603:20)
    at checkAndUpdateNode (file:///data/data/tech.mokum.shine/files/app/vendor.js:67565:16)
    at prodCheckAndUpdateNode (file:///data/data/tech.mokum.shine/files/app/vendor.js:68106:5)
    at Object.eval [as updateDirectives] (ng:///AppModule/AppComponent_Host.ngfactory.js:12:9)
    at Object.updateDirectives (file:///data/data/tech.mokum.shine/files/app/vendor.js:67894:72)
    at Object.checkAndUpdateView (file:///data/data/tech.mokum.shine/files/app/vendor.js:67547:14)
    at ViewRef_.push.../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges (file:///data/data/tech.mokum.shine/files/app/vendor.js:58794:22)
    at ApplicationRef.push.../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick (file:///data/data/tech.mokum.shine/files/app/vendor.js:65217:26)
    at ApplicationRef.push.../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent (file:///data/data/tech.mokum.shine/files/app/vendor.js:65272:14)
    at ApplicationRef.push.../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap (file:///data/data/tech.mokum.shine/files/app/vendor.js:65189:14)
    at file:///data/data/tech.mokum.shine/files/app/vendor.js:64904:81
    at Array.forEach (<anonymous>)
```

By the way: I noticed there is a difference if I suspend by going to the home screen and then resume, which will call ngOnInit again an result in the above call stack, or whether I lock the screen when the app is running en then unlock, which will not call ngOnInit again. So maybe there is something in what you are saying that Android may have different ways of handling resume events.

Any idea as to how we could mitigate this?

**Comment by edusperoni** [comment]
Can you check your manifest and see if android:launchMode is defined as singleTask? It must be, otherwise it'll create a new instance of the app when you open it

**Comment by abhayastudios** [comment]
@edusperoni you are right this solves the issue!

The only thing I am a little worried about is this note in the [Android manifest docs](https://developer.android.com/guide/topics/manifest/activity-element#lmode):

> The other modes — singleTask and singleInstance — are not appropriate for most applications, since they result in an interaction model that is likely to be unfamiliar to users and is very different from most other applications.

I don't really understand why it might no be appropriate for most applications. Do you have any idea in what kind of situations it could cause problems? If I understand correctly I can cause activities to be removed. Should I assume that in NativeScript it will always be safe?

Thanks a lot!

**Comment by NathanaelA** [comment]
NativeScript uses a single Activity for everything so `SingleTask` is the best most for most NS applications to eliminate any weirdness especially with Angular as the flavor.
