### ISSUE TITLE
Cannot handle unexpected exception in Angular application

### ISSUE THREAD

**Issue by mmikirtumov** [NativeScript/nativescript-angular#2177]
**Environment**
 - CLI: 6.5.0
 - Cross-platform modules:
 - Android Runtime: 8.1.0
 - Plugin(s): nativescript-camera, nativescript-image, nativescript-sentry
 - NativeScript-Angular: 8.0.2
 - Angular: 8.0.0
 
**Describe the bug**
Application crashing in unexpected way and angular ErrorHandle, applicationOn(discardedErrorEvent,) and applicationOn(uncaughtErrorEvent,) cannot catch the exception to handle it and crash application (the flag "discardUncaughtJsExceptions": true, does not help)

The exception:
`Calling js method onSaveInstanceState failed
TypeError: Cannot read property '_domId' of undefined`

`
java.lang.Throwable: 
push.../node_modules/@nativescript/core/ui/frame/frame.js.ActivityCallbacksImplementation.onSaveInstanceState(file:///data/data/application.name/files/app/vendor.js:109126:54)
	at push.../node_modules/@nativescript/core/ui/frame/activity.js.NativeScriptActivity.onSaveInstanceState(file:///data/data/application.name/files/app/vendor.js:106904:25)
`
`   at com.tns.Runtime.passExceptionToJsNative(Runtime.java)
    at com.tns.Runtime.passDiscardedExceptionToJs(Runtime.java:89)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1291)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
    at com.tns.Runtime.callJSMethod(Runtime.java:1134)
    at com.tns.NativeScriptActivity.onSaveInstanceState(NativeScriptActivity.java:45)
    at android.app.Activity.performSaveInstanceState(Activity.java:1560)
    at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1394)
    at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4972)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4259)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4318)
    at android.app.ActivityThread.-wrap26
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:7000)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
java.lang.Exception: Calling js method onSaveInstanceState failed
TypeError: Cannot read property '_domId' of undefined
    at com.tns.Runtime.passExceptionToJsNative(Runtime.java)
    at com.tns.Runtime.passDiscardedExceptionToJs(Runtime.java:89)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1291)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
    at com.tns.Runtime.callJSMethod(Runtime.java:1134)
    at com.tns.NativeScriptActivity.onSaveInstanceState(NativeScriptActivity.java:45)
    at android.app.Activity.performSaveInstanceState(Activity.java:1560)
    at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1394)
    at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4972)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4259)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4318)
    at android.app.ActivityThread.-wrap26
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:7000)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)` 

and also

The second exception fired very rare specially after some usage of camera

`java.lang.Throwable: ZoneAwareError(file:///data/data/application.name/files/app/vendor.js:166665:33)
	at push.../node_modules/@nativescript/core/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent(file:///data/data/application.name/files/app/vendor.js:109275:27)
	at push.../node_modules/@nativescript/core/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate(file:///data/data/application.name/files/app/vendor.js:109116:14)
	at push.../node_modules/@nativescript/core/ui/frame/activity.js.NativeScriptActivity.onCreate(file:///data/data/application.name/files/app/vendor.js:106898:25)
`
`
    at com.tns.Runtime.passExceptionToJsNative(Runtime.java)
    at com.tns.Runtime.passDiscardedExceptionToJs(Runtime.java:89)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1291)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
    at com.tns.Runtime.callJSMethod(Runtime.java:1134)
    at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
    at android.app.Activity.performCreate(Activity.java:7258)
    at android.app.Activity.performCreate(Activity.java:7249)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
    at android.app.ActivityThread.-wrap11
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:7000)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
java.lang.Exception: Calling js method onCreate failed
Error: Main entry is missing. App cannot be started. Verify app bootstrap.
    at com.tns.Runtime.passExceptionToJsNative(Runtime.java)
    at com.tns.Runtime.passDiscardedExceptionToJs(Runtime.java:89)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1291)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
    at com.tns.Runtime.callJSMethod(Runtime.java:1134)
    at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
    at android.app.Activity.performCreate(Activity.java:7258)
    at android.app.Activity.performCreate(Activity.java:7249)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
    at android.app.ActivityThread.-wrap11
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:7000)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Expected behavior**
Should call exception handling functions (Errorhandler etc.)

**Comment by arLevi** [comment]
did you ever figure this thing out ?
