### ISSUE TITLE
Angular 10 Main entry is missing. App cannot be started. Verify app bootstrap

### ISSUE THREAD

**Issue by pyrrhicman** [NativeScript/nativescript-angular#2208]
tns info: 
```
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.8.0-rc.4 and the latest available version is 6.8.0.
✔ Component tns-core-modules has 6.5.12 version and is up to date.
✔ Component @nativescript/core has 7.0.0-rc.34 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.
✔ Component tns-ios has 6.5.2 version and is up to date.
```
My package: 
```
  "dependencies": {
    "@angular/animations": "~10.0.0",
    "@angular/cdk": "^10.1.1",
    "@angular/common": "~10.0.0",
    "@angular/compiler": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/elements": "^9.0.6",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "~10.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/material": "10.1.1",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/pwa": "0.900.2",
    "@angular/router": "~10.0.0",
    "@angular/service-worker": "8.2.14",
    "@fortawesome/fontawesome-free": "^5.13.0",
    "@fullcalendar/core": "^5.1.0",
    "@fullcalendar/daygrid": "^5.1.0",
    "@fullcalendar/interaction": "^5.1.0",
    "@fullcalendar/list": "^5.1.0",
    "@nativescript/angular": "~10.0.0",
    "@nativescript/core": "rc",
    "@nativescript/theme": "~2.3.0",
    "@ngrx/data": "^8.6.0",
    "@ngrx/effects": "^8.6.0",
    "@ngrx/entity": "^8.6.0",
    "@ngrx/router-store": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",
    "animejs": "3.1.0",
    "chart.js": "^2.9.3",
    "core-js": "^2.6.9",
    "mapbox-gl": "^1.11.1",
    "nativescript-bottom-navigation": "^2.0.5",
    "nativescript-https": "^1.3.0",
    "nativescript-material-snackbar": "^3.1.11",
    "nativescript-secure-storage": "^2.6.1",
    "ngx-image-cropper": "3.0.3",
    "ngx-mapbox-gl": "^4.8.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.6.2",
    "safe-buffer": "^5.2.1",
    "tns-core-modules": "~6.5.0",
    "tslib": "1.10.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.2",
    "@angular/cli": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@nativescript/schematics": "^10.0.1",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/webpack": "~2.0.0",
    "@types/animejs": "3.1.0",
    "@types/chart.js": "2.9.14",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "25.1.2",
    "@types/mapbox-gl": "^1.11.1",
    "@types/mapbox__polyline": "^1.0.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "25.1.0",
    "jest-preset-angular": "8.0.0",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "nativescript-dev-webpack": "~1.5.1",
    "node-sass": "^4.7.1",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.0"
  }
```
 
**Describe the bug**
After running `npm run clean` and `npm i ` and then postinstall  will run `ngcc --properties es2015 module main --first-only` automatically and compiles for Ivy 
```
> ngcc --properties es2015 module main --first-only

Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/service-worker/config : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @ngrx/store : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
...
```

Now if I run `tns run android --no-hmr`

```
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
...
```
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.lohisportsv1 on device emulator-5554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.lohisportsv1/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.lohisportsv1/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
System.err: 	at android.app.Activity.performCreate(Activity.java:7136)
System.err: 	at android.app.Activity.performCreate(Activity.java:7127)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
System.err: 	... 11 more
```

But It will get fixed If I change something in a tns file to make it just recompile.

```
File change detected. Starting incremental webpack compilation...
Hash: 1c65cdcc0ec6ce9de54f
Version: webpack 4.43.0
Time: 5602ms
Built at: 07/31/2020 7:12:12 PM
                                 Asset       Size  Chunks             Chunk Names
  assets/activity-types-svg/biking.svg   1.07 KiB          [emitted]  
 assets/activity-types-svg/running.svg  860 bytes          [emitted]  
assets/activity-types-svg/swimming.svg   3.11 KiB          [emitted]  
                    assets/battery.svg  736 bytes          [emitted]  
                 assets/battery100.svg  436 bytes          [emitted]  
                  assets/battery25.svg  439 bytes          [emitted]  
                  assets/battery50.svg  439 bytes          [emitted]  
                  assets/battery75.svg  437 bytes          [emitted]  
         assets/icons/icon-128x128.png   1.22 KiB          [emitted]  
         assets/icons/icon-144x144.png   1.36 KiB          [emitted]  
         assets/icons/icon-152x152.png   1.39 KiB          [emitted]  
         assets/icons/icon-192x192.png   1.75 KiB          [emitted]  
         assets/icons/icon-384x384.png   3.47 KiB          [emitted]  
         assets/icons/icon-512x512.png   4.89 KiB          [emitted]  
           assets/icons/icon-72x72.png  792 bytes          [emitted]  
           assets/icons/icon-96x96.png  958 bytes          [emitted]  
            assets/images/login-bg.jpg   3.28 MiB          [emitted]  
                assets/images/logo.png   23.4 KiB          [emitted]  
     assets/images/oura_logo_black.png   9.65 KiB          [emitted]  
                    assets/loading.gif     11 KiB          [emitted]  
                    assets/noImage.png   1.56 KiB          [emitted]  
       assets/social-pics/facebook.png   4.75 KiB          [emitted]  
         assets/social-pics/garmin.png   6.21 KiB          [emitted]  
      assets/social-pics/instagram.png   15.8 KiB          [emitted]  
       assets/social-pics/snapchat.png   8.91 KiB          [emitted]  
         assets/social-pics/strava.jpg     12 KiB          [emitted]  
        assets/social-pics/twitter.png   6.16 KiB          [emitted]  
        assets/social-pics/untappd.png   15.4 KiB          [emitted]  
                   assets/teamlogo.png   29.9 KiB          [emitted]  
                             bundle.js    793 KiB  bundle  [emitted]  bundle
               fonts/fa-brands-400.ttf    129 KiB          [emitted]  
              fonts/fa-regular-400.ttf   33.3 KiB          [emitted]  
                fonts/fa-solid-900.ttf    189 KiB          [emitted]  
                             vendor.js   16.9 MiB  vendor  [emitted]  vendor
 + 1 hidden asset
Entrypoint bundle = runtime.js vendor.js bundle.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy namespace object 160 bytes {bundle} [built]
[./app/_helpers/router.service.tns.ts] 1010 bytes {bundle} [built]
[./app/_services/alert.service.tns.ts] 1.34 KiB {bundle} [built]
[./app/_services/authentication.service.tns.ts] 3.72 KiB {bundle} [built]
[./app/_store/actions/auth.action.ts] 5.88 KiB {bundle} [built]
[./app/_store/app.module.effect.ts] 585 bytes {bundle} [built]
[./app/_store/app.module.reducer.ts] 1.88 KiB {bundle} [built]
[./app/_store/effects/activity.effect.ts] 3.7 KiB {bundle} [built]
[./app/_store/effects/auth.effect.ts] 8.49 KiB {bundle} [built]
[./app/app-routing.module.tns.ts] 1.31 KiB {bundle} [built]
[./app/app.component.tns.ts] 996 bytes {bundle} [built]
[./app/app.module.tns.ts] 3.83 KiB {bundle} [built]
[./app/public/login/login.component.ts] 17.3 KiB {bundle} [built]
[./environments/environment.ts] 1.04 KiB {bundle} [built]
[./main.tns.ts] 2.08 KiB {bundle} [built]
    + 587 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
Successfully transferred all files on device emulator-5554.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.lohisportsv1 on device emulator-5554.
JS: nativescript-https > Disabled SSL pinning by default
JS: Angular is running in development mode. Call enableProdMode() to enable production mode.
```

**To Reproduce**
Let me know I might be able to create a sample project

**Expected behavior**
Just start working normally without need to edit a file to make it recompile

**Sample project**
I used workspace sample project given for angular schematics v 10

**Additional context**
One other thing when I run Nativescript side of project and I want to run Angular side with ng serve
I will get the following error which to get rid of it I need to run `npm run clean` and `npm i` again. 
But is it normal way? Shouldn't they work together.
```
TypeError: Class constructor BehaviorSubject cannot be invoked without 'new'
    at DevtoolsDispatcher.ActionsSubject [as constructor] (store.js:123)
    at new DevtoolsDispatcher (store-devtools.js:165)
    at ActionsSubject_Factory (store.js:145)
    at Object.DevtoolsDispatcher_Factory [as factory] (store-devtools.js:167)
    at R3Injector.hydrate (core.js:11348)
    at R3Injector.get (core.js:11170)
    at injectInjectorOnly (core.js:801)
    at Module.ɵɵinject (core.js:805)
    at Object.StoreDevtools_Factory [as factory] (store-devtools.js:876)
    at R3Injector.hydrate (core.js:11348)
```

**Comment by NathanWalker** [comment]
Thank you @pyrrhicman this is related to es2017 targeting in latest rc's. May want to check if store-devtools has a newer version? I'll help look as well.

**Comment by pyrrhicman** [comment]
> Thank you @pyrrhicman this is related to es2017 targeting in latest rc's. May want to check if store-devtools has a newer version? I'll help look as well.

Thanks, It was it. I just needed to update 
```
    "@ngrx/data": "^9.2.0",
    "@ngrx/effects": "^9.2.0",
    "@ngrx/entity": "^9.2.0",
    "@ngrx/router-store": "^9.2.0",
    "@ngrx/store": "^9.2.0",
    "@ngrx/store-devtools": "^9.2.0"
```
and it's good now. I hope one day comes that I understand tsconfig libs and target.

although `Error: Main entry is missing. App cannot be started. Verify app bootstrap ` error still exist.

**Comment by NathanWalker** [comment]
> Main entry is missing.

I recall that may have something to do with webpack.config.js. Did you try deleting your webpack.config entirely and doing a clean to let @nativescript/webpack drop you in a brand new one using latest configurations?

**Comment by pyrrhicman** [comment]
> > Main entry is missing.
> 
> I recall that may have something to do with webpack.config.js. Did you try deleting your webpack.config entirely and doing a clean to let @nativescript/webpack drop you in a brand new one using latest configurations? If not, definitely try deleting the one in your project and let it get replaced with the new one when running again from @nativescript/webpack ~2.0.0

 I DID it 👍  
Well It wasn't library, It was my code, Just fixed some errors and it boots perfectly now.

Thanks for support.

**Comment by pyrrhicman** [comment]
`TypeError: Class constructor BehaviorSubject cannot be invoked without 'new'` was not gone And
I needed to disable Ivy at least for development of Angular side 
so I added this to tsconfig.app.json
```
"angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy": false
  }
```
and now I run my code with `tns run android --bundle`
