### ISSUE TITLE
Calling Theme.getMode() etc. from @nativescript/theme causes app crash with angular 10

### ISSUE THREAD

**Issue by michaelprummer** [NativeScript/nativescript-angular#2216]
**Environment**
nativescript 6.8
tns-android: 6.5.3
theme: 2.3.3
 
**Describe the bug**
Using theme import causing angular app to crash with undefiend mainScreen.
Was working fine with angular 9. I was trying with multiple example apps posted here an got the same error below.

**To Reproduce**
Take any ns angular 10 app for example:
https://github.com/mahmoudajawad/nativescript-pokedex

Add an import to @nativescript/theme and call any theme method for e.g.:

import { Theme } from '@nativescript/theme';
Theme.getMode()

It will crash with the following error:

´

Error log:
`
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.ngsample on device emulator-5554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'mainScreen' of undefined
System.err: File: (file: node_modules\@nativescript\theme\index.js:24:0)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/@nativescript/theme/index.js(file: node_modules\@nativescript\theme\index.js:24:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at ./app/app.component.tns.ts(file: src\app\app.component.tns.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at ./app/app.module.tns.ts(file: src\app\app.module.tns.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at (file: src\main.tns.ts:1:106)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.ngsample/files/app/bundle.js:299:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Cannot read property 'mainScreen' of undefined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'mainScreen' of undefined
System.err: File: (file: node_modules\@nativescript\theme\index.js:24:0)
System.err:
System.err: StackTrace:
System.err: ../node_modules/@nativescript/theme/index.js(file: node_modules\@nativescript\theme\index.js:24:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at ./app/app.component.tns.ts(file: src\app\app.component.tns.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at ./app/app.module.tns.ts(file: src\app\app.module.tns.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at (file: src\main.tns.ts:1:106)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.ngsample/files/app/bundle.js:299:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Cannot read property 'mainScreen' of undefined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'mainScreen' of undefined
System.err: File: (file: node_modules\@nativescript\theme\index.js:24:0)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/@nativescript/theme/index.js(file: node_modules\@nativescript\theme\index.js:24:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at ./app/app.component.tns.ts(file: src\app\app.component.tns.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at ./app/app.module.tns.ts(file: src\app\app.module.tns.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at (file: src\main.tns.ts:1:106)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.ngsample/files/app/bundle.js:299:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:74:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.ngsample/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Cannot read property 'mainScreen' of undefined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
System.err:     ... 8 more
`

**Comment by michaelprummer** [comment]
Was fixed for me with new version 2.5.0...
