### ISSUE TITLE
Error After Adding RadSideDrawer as instructed in the official Documents

### ISSUE THREAD

**Issue by mukaz4god** [NativeScript/nativescript-angular#2245]
I have been encountering an error when trying to add RADSIDEDRAWER to my Nativescript-Angular-Project since 5 days ago. I have installed the plugin as directed in the nativescript doc. Also After Installation I have deleted the (Node_module, Platforms, Hook, Webpack.config.js,package-lock.json folder and run npm install) but still no luck. Please any assistance will be highly appreciated
--------------------------------------------------------------------------------------------------------
Successfully installed on device with identifier 'BVK6R20525018511'.
Restarting application on device BVK6R20525018511...
Successfully synced application org.nativescript.nsngcourse on device BVK6R20525018511.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Class extends value undefined is not a constructor or null
System.err: File: (file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.common.js:27:66)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js(file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.common.js:27:66)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js(file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:155379:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-sidedrawer/angular/fesm2015/nativescript-ui-sidedrawer-angular.js(file: node_modules\nativescript-ui-sidedrawer\angular\fesm2015\nativescript-ui-sidedrawer-angular.js:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.ts(file: src\app\app.module.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:783:73)
System.err:     at ./main.ts(file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:849:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err:
System.err: TypeError: Class extends value undefined is not a constructor or null
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Class extends value undefined is not a constructor or null
System.err: File: (file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.common.js:27:66)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js(file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.common.js:27:66)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js(file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:155379:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-sidedrawer/angular/fesm2015/nativescript-ui-sidedrawer-angular.js(file: node_modules\nativescript-ui-sidedrawer\angular\fesm2015\nativescript-ui-sidedrawer-angular.js:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.ts(file: src\app\app.module.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:783:73)
System.err:     at ./main.ts(file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:849:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err: 
System.err: TypeError: Class extends value undefined is not a constructor or null
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6654)
System.err:     at android.app.ActivityThread.-wrap2(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:109)
System.err:     at android.os.Looper.loop(Looper.java:166)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7555)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Class extends value undefined is not a constructor or null
System.err: File: (file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.common.js:27:66)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js(file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.common.js:27:66)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-sidedrawer\ui-sidedrawer.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js(file:///data/data/org.nativescript.nsngcourse/files/app/vendor.js:155379:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-sidedrawer/angular/fesm2015/nativescript-ui-sidedrawer-angular.js(file: node_modules\nativescript-ui-sidedrawer\angular\fesm2015\nativescript-ui-sidedrawer-angular.js:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.ts(file: src\app\app.module.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:783:73)
System.err:     at ./main.ts(file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:849:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.nsngcourse/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Class extends value undefined is not a constructor or null
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1123)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6636)
System.err:     ... 8 more

**Comment by mukaz4god** [comment]
finally go it work by downgraded  to 8.0.1
