### ISSUE TITLE
RadCalendar can not import module in Angular

### ISSUE THREAD

**Issue by minhson95th** [NativeScript/nativescript-angular#2339]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):
 - NativeScript-Angular:
 - Angular:
 
**Describe the bug**

after `tns plugin add nativescript-ui-calendar` and imported in an ngModule in my app. But when `tns run android` can not run project
![image](https://user-images.githubusercontent.com/46039866/112448545-15275c80-8d85-11eb-9682-a4e44c8c9e18.png)
the error:
`System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules\nativescript-ui-calendar\ui-calendar.common.js:283:0)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-calendar/ui-calendar.common.js(file: node_modules\nativescript-ui-calendar\ui-calendar.common.js:283:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-calendar\ui-calendar.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-calendar/ui-calendar.js(file:///data/data/org.nativescript.coretech6/files/app/vendor.js:157427:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-calendar/angular/fesm2015/nativescript-ui-calendar-angular.js(file: node_modules\nativescript-ui-calendar\angular\fesm2015\nativescript-ui-calendar-angular.js:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.ts(file: src\app\app.module.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.coretech6/files/app/bundle.js:9283:73)
System.err:     at ./main.ts(file:///data/data/org.nativescript.coretech6/files/app/bundle.js:9342:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.coretech6/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err:
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules\nativescript-ui-calendar\ui-calendar.common.js:283:0)
System.err:
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-calendar/ui-calendar.common.js(file: node_modules\nativescript-ui-calendar\ui-calendar.common.js:283:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-calendar\ui-calendar.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-calendar/ui-calendar.js(file:///data/data/org.nativescript.coretech6/files/app/vendor.js:157427:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-calendar/angular/fesm2015/nativescript-ui-calendar-angular.js(file: node_modules\nativescript-ui-calendar\angular\fesm2015\nativescript-ui-calendar-angular.js:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.ts(file: src\app\app.module.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.coretech6/files/app/bundle.js:9283:73)
System.err:     at ./main.ts(file:///data/data/org.nativescript.coretech6/files/app/bundle.js:9342:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.coretech6/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6484)
System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:220)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7397)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules\nativescript-ui-calendar\ui-calendar.common.js:283:0)
System.err:
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-calendar/ui-calendar.common.js(file: node_modules\nativescript-ui-calendar\ui-calendar.common.js:283:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-calendar\ui-calendar.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-calendar/ui-calendar.js(file:///data/data/org.nativescript.coretech6/files/app/vendor.js:157427:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-calendar/angular/fesm2015/nativescript-ui-calendar-angular.js(file: node_modules\nativescript-ui-calendar\angular\fesm2015\nativescript-ui-calendar-angular.js:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.ts(file: src\app\app.module.ts:1:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.coretech6/files/app/bundle.js:9283:73)
System.err:     at ./main.ts(file:///data/data/org.nativescript.coretech6/files/app/bundle.js:9342:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.coretech6/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1183)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6479)
System.err:     ... 8 more` 
and `package.json`
![image](https://user-images.githubusercontent.com/46039866/112448825-5e77ac00-8d85-11eb-84ef-51b817963e43.png)

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by tehartos** [comment]
I have the same problem. Any fix?
