### ISSUE TITLE
Error on run blank Angular project

### ISSUE THREAD

**Issue by juniorschen** [NativeScript/nativescript-angular#2376]
Cannot run default application.

Steps:
ns new myCoolApp --angular
ns run android 

And:

Error: Not supported
    at eval (eval at initializeCompilerCli (C:\Users\junio\Documents\NS\myCoolApp\node_modules\@ngtools\webpack\src\ivy\plugin.js:528:40), <anonymous>:3:1)
    at AngularWebpackPlugin.initializeCompilerCli (C:\Users\junio\Documents\NS\myCoolApp\node_modules\@ngtools\webpack\src\ivy\plugin.js:528:95)
    at C:\Users\junio\Documents\NS\myCoolApp\node_modules\@ngtools\webpack\src\ivy\plugin.js:124:73
    at Hook.eval [as callAsync] (eval at create (C:\Users\junio\Documents\NS\myCoolApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\junio\Documents\NS\myCoolApp\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (C:\Users\junio\Documents\NS\myCoolApp\node_modules\webpack\lib\Compiler.js:1148:28)
    at C:\Users\junio\Documents\NS\myCoolApp\node_modules\webpack\lib\Watching.js:214:19
    at eval (eval at create (C:\Users\junio\Documents\NS\myCoolApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Users\junio\Documents\NS\myCoolApp\node_modules\@nativescript\webpack\dist\plugins\WatchStatePlugin.js:22:13
    at Hook.eval [as callAsync] (eval at create (C:\Users\junio\Documents\NS\myCoolApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\junio\Documents\NS\myCoolApp\node_modules\tapable\lib\Hook.js:18:14)
    at run (C:\Users\junio\Documents\NS\myCoolApp\node_modules\webpack\lib\Watching.js:168:33)
    at C:\Users\junio\Documents\NS\myCoolApp\node_modules\webpack\lib\Watching.js:163:6
    at Compiler.readRecords (C:\Users\junio\Documents\NS\myCoolApp\node_modules\webpack\lib\Compiler.js:973:5)
    at run (C:\Users\junio\Documents\NS\myCoolApp\node_modules\webpack\lib\Watching.js:159:26)
    at Watching._go (C:\Users\junio\Documents\NS\myCoolApp\node_modules\webpack\lib\Watching.js:218:3)

**Comment by juniorschen** [comment]
package:
"dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@nativescript/angular": "^13.0.0",
    "@nativescript/core": "~8.2.0",
    "@nativescript/theme": "~3.0.2",
    "rxjs": "~7.5.0",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.0",
    "@angular/compiler-cli": "~13.2.0",
    "@nativescript/android": "8.2.2",
    "@nativescript/types": "~8.2.0",
    "@nativescript/webpack": "~5.0.6",
    "@ngtools/webpack": "~13.2.0",
    "typescript": "~4.5.5"
  }

**Comment by juniorschen** [comment]
Update node and works fine
