### ISSUE TITLE
project with barcodescanner doesn't compile

### ISSUE THREAD

**Issue by sclausen** [NativeScript/nativescript-angular#238]
Simply by adding [EddyVerbruggen/nativescript-barcodescanner](https://github.com/EddyVerbruggen/nativescript-barcodescanner) to a project, the whole programm doesn't compile anymore.

```
Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.zxing.pdf417.PDF417ResultMetadata conflict: /home/username/projects/NativeScript/nativescript-angular/ng-sample/platforms/android/build/intermediates/exploded-aar/barcodescanner-release/jars/classes.jar and /home/username/projects/NativeScript/nativescript-angular/ng-sample/platforms/android/build/intermediates/exploded-aar/barcodescanner-release-2.0.1/jars/classes.jar                                                                  
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:39)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED
```

**Comment by hdeshev** [comment]
I'd never seen that error before. @Plamen5kov any ideas? Could this be an issue with the barcode scanner plugin?

**Comment by Plamen5kov** [comment]
Hi @sclausen 
* go to platforms/android`
* delete the `build` folder
* build again

**Comment by sclausen** [comment]
Not that I didn't tried that before, but you seem to have magic influence on how my stuff works :grin:
Thanks, that helped!
