### ISSUE TITLE
Angular Location.replaceState("<path>") not working

### ISSUE THREAD

**Issue by manjunathshetty** [NativeScript/nativescript-angular#240]
Here is the code sample 

```
import { Location } from '@angular/common';
...
constructor(private _page: Page, private _router: Router, private _location:Location) {

 }
....
ngOnInit(){
        console.log("Initiating Home View");
        if(!this.isLoggedIn){
            console.log("Not logged in. Navigating to main page");
            this._location.replaceState('/main');
        }
    }

```
 I am getting this error 

```
Error: Not implemented
JS:     at NSLocationStrategy.replaceState (/data/data/org.nativescript.scrap/files/app/tns_modules/nativescript-angular/router/ns-location-strategy.js:42:15)
JS:     at Location.replaceState (/data/data/org.nativescript.scrap/files/app/tns_modules/@angular/common/src/location/location.js:55:31)
JS:     at HomeComponent.ngOnInit (/data/data/org.nativescript.scrap/files/app/components/home.component.js:15:28)
JS:     at DebugAppView._View_HomeComponent_Host0.detectChangesInternal (HomeComponent_Host.template.js:28:92)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.scrap/files/app/tns_modules/@angular/core/src/linker/view.js:200:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.scrap/files/app/tns_modules/@angular/core/src/linker/view.js:289:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nativescript.scrap/files/app/tns_modules/@angular/core/src/linker/view.js:215:37)
JS:     at DebugAppView.AppView.detectChangesInternal (/data/data/org.nativescript.scrap/files/app/tns_modules/@angular/core/src/linker/view.js:210:14)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.scrap/files/app/tns_modules/@angular/core/src/linker/view.js:200:14)
JS:     at DebugAppView.detect

```

**Comment by nsndeck** [comment]
Indeed this method is not implemented you could use `router.navigate` instead:

```JavaScript
this._router.navigate('/main');
```

**Comment by manjunathshetty** [comment]
@nsndeck but i wanted to replace the navigation history so that in android pressing back button will close the app instead of going back to previous page. Is there any way i can achieve this ?. I also tried registering to android back button press event but that wont close the app. I just want to erase the navigation history. (May be multiple page history)

**Comment by nsndeck** [comment]
Unfortunately with the current version of NativeScript-Angular you cannot achieve such functionality. We considered adding such feature, but we decided to wait for the `new router` which `angular` team should release soon. Then we will rewrite our plugin to use the new router and will add this functionality since it is very common (we don't see a point to implement this feature and then rewrite it again). So you can count that this functionality will be available with some of the next releases.

**Comment by manjunathshetty** [comment]
Sure thanks @nsndeck

**Comment by johnnyzen** [comment]
Any update on this? Why is it closed?

**Comment by GeorgeFarfan** [comment]
Hi 

Do you know if this can be done already?
