### ISSUE TITLE
Exception on newly created project - both --tsc and --ng

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-angular#358]
_From @jvzanatta on July 21, 2016 1:29_

Hi. I'm having this weird log when create a new project with **tns create AppName --ng** and then run with **tns build android**. Same happens if i change --ng for --tsc. Any workarounds?

Thanks in advance.

```
JS: EXCEPTION: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
JS: STACKTRACE:
JS: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
JS:     at resolvePromise (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:496:32)
JS:     at /data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:473:14
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:281:29)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:46:41)
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:280:35)
JS:     at Zone.run (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:174:44)
JS:     at /data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:529:58
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:314:38)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:37:41)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:313:43)
JS: Unhandled Promise rejection: this.page.frame._getNavBarVisible is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: this.page.frame._getNavBarVisible is not a function
JS: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
```

_Copied from original issue: NativeScript/nativescript-cli#1938_

**Comment by vakrilov** [comment]
Hi @jvzanatta
Just tried that and it worked as expected:
```
tns create AppName --ng
cd AppName
tns run android
```

Here is my setup:
```
$ tns --version  // 2.1.1
$ node -v // 4.4.5
$ npm -v // 2.15.5
```

**Comment by jvzanatta** [comment]
Weird. Mine is 
`
$ tns --version  // 2.1.1
$ node -v // 4.4.7
$ npm -v // 3.10.5
`
I keep getting errors and warnings on even the smallest of modifications. Like if I create a new page with <Page ...> instead of <GridLayout>. I'm on Xubuntu btw, which OS are you on?

**Comment by vakrilov** [comment]
I tried on mac. 
Btw, you should not use `Page` when using angular. The framework will take care of creating and navigating pages for you when using angular(that might be that cause of the error you are getting).

If you need to get hold of the current page instance - you can inject `Page` param in you component's constructor.

**Comment by jvzanatta** [comment]
Did not know that about the Page. Thanks. I'm starting to get lost between the many tutorials I found online, some in JS, some using Angular, and so on...

**Comment by vakrilov** [comment]
No problem - just let us know if you continue to get errors.

I will close the issue for know - please reopen if needed.
