### ISSUE TITLE
Telerik 1.2.0 Side Drawer NullPointerException Bug (App Attached)

### ISSUE THREAD

**Issue by jwuliger** [NativeScript/nativescript-angular#388]
**Bug Details**

Error occurs when using RadSideDrawer when navigating using [nsRouterLink]. This error only happens on Android. Please see link to the seed app. App is also attached to this Issue.

The app builds and run on both the emulators and my device. Each running Android 6 API 23.

**Error Stack**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
at com.telerik.android.primitives.widget.sidedrawer.transitions.DrawerTransitionBase.getFrontView(DrawerTransitionBase.java:171)
at com.telerik.android.primitives.widget.sidedrawer.transitions.DrawerTransitionBase.setProgress(DrawerTransitionBase.java:76)
at com.telerik.android.primitives.widget.sidedrawer.transitions.DrawerTransitionBase.onEnded(DrawerTransitionBase.java:226)
at com.telerik.android.primitives.widget.sidedrawer.transitions.DrawerTransitionBase.run(DrawerTransitionBase.java:221)
at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1119)
at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
at android.view.Choreographer.doCallbacks(Choreographer.java:695)
at android.view.Choreographer.doFrame(Choreographer.java:628)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Development Environment & Details**
- Windows 10
- Node: 6.3.1
- NPM: 3.10.6
- Latest Stable version of {N} tooling (tns-android v2.1.1)

**NativeScript Angular 2 Seed with Telerik Drawer**

https://github.com/ntrp/nativescript-ng2-drawer-seed  from the {N} Blog Article https://www.nativescript.org/blog/this-week-in-nativescript-august-1st

Link to the app: (Unmodified from the Master branch of the seed app)

[nativescript-ng2-drawer-seed-master.zip](https://github.com/NativeScript/nativescript-angular/files/405144/nativescript-ng2-drawer-seed-master.zip)

Any help will be greatly appreciated. Thanks for looking into this!

**Comment by NickIliev** [comment]
Issue is not reproducible with the latest NativeScript modules and the new plugin nativescript-pro-ui
