### ISSUE TITLE
[Android] [Modal] Error: Expected valid android.content.Context instance

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-angular#416]
# Problem

When you call `this.modalService.showModal` in `constructor`, `ngOnInit`, or `ngAfterViewInit` this error gets thrown:

```
JS: EXCEPTION: Error: Uncaught (in promise): Error: Expected valid android.content.Context instance.
JS: STACKTRACE:
JS: Error: Uncaught (in promise): Error: Expected valid android.content.Context instance.
JS:     at resolvePromise (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:516:32)
JS:     at /data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:552:18
JS:     at ZoneDelegate.invokeTask (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:323:38)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/com.roblav96.sandbox/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:44:41)
JS:     at ZoneDelegate.invokeTask (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:322:43)
JS:     at Zone.runTask (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:223:48)
JS:     at drainMicroTaskQueue (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:455:36)
JS: Unhandled Promise rejection: Expected valid android.content.Context instance. ; Zone: angular ; Task: Promise.then ; Value: Error: Expected valid android.content.Context instance. Error: Expected valid android.content.Context instance.
JS:     at Page.View._onAttached (/data/data/com.roblav96.sandbox/files/app/tns_modules/ui/core/view.js:137:19)
JS:     at Page._showNativeModalView (/data/data/com.roblav96.sandbox/files/app/tns_modules/ui/page/page.js:133:14)
JS:     at Page.showModal (/data/data/com.roblav96.sandbox/files/app/tns_modules/ui/page/page-common.js:202:18)
JS:     at /data/data/com.roblav96.sandbox/files/app/tns_modules/nativescript-angular/directives/dialogs.js:52:32
JS:     at ZoneDelegate.invoke (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:290:29)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvoke (/data/data/com.roblav96.sandbox/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:53:41)
JS:     at ZoneDelegate.invoke (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:289:35)
JS:     at Zone.run (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:183:44)
JS:     at /data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:549:58
JS:     at ZoneDelegate.invokeTask (/data/data/com.roblav96.sandbox/files/app/tns_modules/zone.js/dist/zone-node.js:323:38)
JS: Error: Uncaught (in promise): Error: Expected valid android.content.Context instance.
```
# Resolve

Throwing a `setTimeout` resolves the issue.

``` typescript
ngOnInit() {
    setTimeout(() => {
        this.modalService.showModal(ModalModule, {
            context: {
                androidIcon: 0xf38f,
                iosIcon: 0xf250,
                title: 'Read/Write SMS',
                desc: 'So you don\'t have to =]',
            },
            fullscreen: false,
        }).then((result: boolean) => {
            result = (typeof result == 'boolean') ? result : false
            global.tnsconsole.log('showModal > result', result)
        })
    }, 1000)
}
```

Not exactly the way it should work.

**Comment by vakrilov** [comment]
Works properly with `nativescript-angular@1.1.2` and `tns-core-modules@2.3.0`.


**Note**:  There is no need to use the the `modal-dialog-host` directive. Pass an instance of `            ViewContainerRef` to the dialog options when calling `showModal()` instead (more info [in the docs](http://docs.nativescript.org/angular/ui/dialogs.html#custom-dialog)).

**Comment by thinkblue36** [comment]
@roblav96 yeah works with setTiemout() even when passing 0 as timeout.
