### ISSUE TITLE
Android only: Navigating back using angular `location.back()` results in: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#437]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:288)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:189)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:189)
	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
	at a
```

I wish I could provide exact repro steps but this happens about 90% of the time when using `this.location.back()` from a route using `page-router-outlet`.
Using rc.5 with `next` tag.

This behavior can be exhibited if running [ShoutOutPlay](https://github.com/NathanWalker/ShoutOutPlay) latest on android (from latest dev branch), if you login, then go to record then navigate back.
Steps:
* search for results
* then click mic (top right) to reveal record screen again then click back arrow.
* You should get the above crash about 90% of time.

**Comment by NathanWalker** [comment]
This issue is a showstopper for Android at the moment. Appears to happen 95% of time when using `location.back()` now.

**Comment by NathanWalker** [comment]
Upon further investigation, this is related to `RadListView` and usage of a swipe template.
Android only issue: Anytime you have a view template using a swipe template like:
```
<GridLayout *tkListItemSwipeTemplate rows="auto" columns="100,*,100" class="list-item-swipe">
      <Button id="editBtn" text="Edit" class="btn edit-btn" row="0" col="0" (tap)="edit($event)"></Button>
      <Button id="deleteBtn" text="Delete" class="btn delete-btn" row="0" col="2" (tap)="remove($event)"></Button>
    </GridLayout>
```
When you navigate to a page route, then use `location.back()`, having that swipe template will cause the above crash. Removing the swipe template makes the issue go away and things work as normal again. Going to report on telerik-ui repo.

**Comment by NathanWalker** [comment]
Turns out it isn't just with RadListView... it can happen randomly with any kind of view setup.
Here's the full logcat:
```
09-06 20:12:05.007  7040  7040 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:288)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.View.layout(View.java:16630)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.View.layout(View.java:16630)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
09-06 20:12:05.007  7040  7040 W System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:189)
09-06 20:12:05.007  7040  7040 W System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.View.layout(View.java:16630)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
09-06 20:12:05.007  7040  7040 W System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:189)
09-06 20:12:05.007  7040  7040 W System.err: 	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.View.layout(View.java:16630)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.View.layout(View.java:16630)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.View.layout(View.java:16630)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
09-06 20:12:05.007  7040  7040 W System.err: 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.View.layout(View.java:16630)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.os.Looper.loop(Looper.java:148)
09-06 20:12:05.007  7040  7040 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-06 20:12:05.007  7040  7040 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 20:12:05.007  7040  7040 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-06 20:12:05.007  7040  7040 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by NathanWalker** [comment]
https://github.com/telerik/nativescript-ui/issues/541#issuecomment-246007606

**Comment by NathanWalker** [comment]
Closing this here since it is being tracked here: https://github.com/telerik/nativescript-ui/issues/541#issuecomment-246007606

**Comment by miaupip** [comment]
Hello
The URL doesn't work anymore.
How did you fix it? i'm have the same problem.

**Comment by dgomezs** [comment]
@miaupip I reported the issue on the feedback repository. Did you manage to find a workaround?

**Comment by miaupip** [comment]
@dgomezs 
Thank you for your info. 
Telerik fixed it, in the release 1.6.0. Since this release it's working (I use the same code as before, i have only updated the npm nativescript-telerik-ui package).

I hope it's also the solution for your problem.

Fixed RadlistView issues:
- 'swipeActions' stops working if you navigate to a new Page and come back (android)
- App crashes when navigating back to a ListView with a header/footer

If you are interested, here are the release-notes.
http://docs.telerik.com/devtools/nativescript-ui/release-notes

**Comment by dgomezs** [comment]
@miaupip I'm using the latest version but still got this issue. Thank you for the response. I will keep investigating

**Comment by miaupip** [comment]
@dgomezs 
Do you have some source code?
