### ISSUE TITLE
No provider for PlatformLocation!

### ISSUE THREAD

**Issue by Sulman633** [NativeScript/nativescript-angular#485]
I am getting the following error while I am trying to implement simple routing:

No provider for PlatformLocation!

Error: No provider for PlatformLocation!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (/data/data/org.nativescript.nightlivefront/files/app/tns_modules/@angular/core/bundles/core.umd.js:1248:38)
    at NoProviderError.AbstractProviderError [as constructor] (/data/data/org.nativescript.nightlivefront/files/app/tns_modules/@angular/core/bundles/core.umd.js:1703:20)
    at new NoProviderError (/data/data/org.nativescript.nightlivefront/files/app/tns_modules/@angular/core/bundles/core.umd.js:1734:20)
    at ReflectiveInjector_._throwOrNull (/data/data/org.nativescript.nightlivefront/files/app/tns_modules/@angular/core/bundles/core.umd.js:3331:23)
    at ReflectiveInjector_._getByKeyDefault (/data/data/org.nativescript.nightlivefront/files/app/tns_modules/@angular/core/bundles/core.umd.js:3359:29)
    at ReflectiveInjector_._getByKey (/data/data/org.nativescript.nightlivefront/files/app/tns_modules/@angular/core/bundles/core.umd.js:3322:29)
    at ReflectiveInjector_.get (/data/data/org.nativescript.nightlivefront/files/app/tns_modules/@angular/core/bundles/core.umd.js:3131:25)
    at NgModuleInjector.Object.defineProperty.get (AppComponentModule.ngfactory.js:104:119)
    at NgModuleInjector.Object.defineProperty.get (AppComponentModule.ngfactory.js:109:84)

This error occurs when I add an array of navigatableComponents to my main.ts declarations, here is a screen shot:
![maints](https://cloud.githubusercontent.com/assets/11000928/19024334/a0ecd610-88cf-11e6-98db-d31e27eebeaf.PNG)

This is what my routing file looks like:
![routing](https://cloud.githubusercontent.com/assets/11000928/19024337/ad5705ce-88cf-11e6-9999-de49ff6cf36f.PNG)

and finally my package.json file:
![packagejson](https://cloud.githubusercontent.com/assets/11000928/19024339/b7e2a4da-88cf-11e6-905c-364cb43575a3.PNG)

Could some please explain why this is happening and what the resolution is? Thank you.

**Comment by tsonevn** [comment]
Hi @Sulman633,
Perhaps the problem is due  missing  `NativeScriptRouterModule` inside `imports` the  in `main.ts` file. You could review the example below.
`main.ts`

```
import { platformNativeScriptDynamic, NativeScriptModule } from "nativescript-angular/platform";
import { routes, routableComponents } from "./app.routes";
import { AppComponent } from "./app.component";
import { NgModule } from "@angular/core";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { NativeScriptFormsModule } from "nativescript-angular/forms";

@NgModule({
    declarations: [
        AppComponent,
        routableComponents,
    ],
    bootstrap: [AppComponent],
    imports: [
        NativeScriptModule,
        NativeScriptFormsModule,
        NativeScriptRouterModule,
        NativeScriptRouterModule.forRoot(routes),
    ],
})
class AppComponentModule { }

platformNativeScriptDynamic().bootstrapModule(AppComponentModule);
```

I hope this will help.

**Comment by Sulman633** [comment]
@tsonevn Thank you, very much that worked!

**Comment by claupokertm** [comment]
Same thing, had to import the NativeScriptRouterModule clean also
Thanks @tsonevn
