### ISSUE TITLE
nativescript angular build --release fails, but not build debug

### ISSUE THREAD

**Issue by calebeaires** [NativeScript/nativescript-angular#627]
App is installed and works on build/run version, but not on ``build --release``. I have tried to find the problem but I was not able to spot the cause of that. Here is the debug console print from the fail

```

java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 
Error calling module function 
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/app.module.js', line: 4, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/app.module.js', line: 4, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/app.module.js', line: 4, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4731)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: com.tns.NativeScriptException: 
Error calling module function 
Error calling module function 
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/app.module.js', line: 4, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/app.module.js', line: 4, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/app.module.js', line: 4, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.somecompany.myapp/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:514)
	at com.tns.Runtime.run(Runtime.java:509)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
	... 8 more
```

Line 4 from app.module.ts

```
import { NativeScriptRouterModule } from 'nativescript-angular';
```

Line 4 from app.module.js
```
var nativescript_angular_1 = require('nativescript-angular');
```

Tested on Moto Z, Moto X Style (fails on both)
Nativescript 2.4.2
Plugins:
```
    "nativescript-admob": "^1.3.0",
    "nativescript-angular": "1.2.0",
    "nativescript-angular-snapshot": "1.2.0-5.2.361-2",
    "nativescript-clipboard": "^1.1.5",
    "nativescript-insomnia": "^1.2.0",
    "nativescript-orientation": "^1.5.4",
    "nativescript-social-share": "^1.3.2",
    "nativescript-sqlite": "^1.1.2",
    "nativescript-telerik-ui": "^1.5.1",
    "nativescript-theme-core": "^0.2.1",
    "nativescript-toast": "^1.4.5",
```

Instructions I have made to build --release: [Publishing a NativeScript Android App in Google Play](https://docs.nativescript.org/angular/publishing/publishing-android-apps.html)

**Comment by NickIliev** [comment]
@calebeaires the imports for [NativeScriptRouterModule](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#configuration) is now 
```
import { NativeScriptRouterModule } from "nativescript-angular/router";
```

Apart from that, you can try to update your version of nativescript-angular to the lastest stable.

**Comment by calebeaires** [comment]
It worked. Very thanks!
