### ISSUE TITLE
"enableTracing: true" leads to an exception in @angular/router

### ISSUE THREAD

**Issue by dvabuzyarov** [NativeScript/nativescript-angular#650]
This bug is reproducible with sample-Groceries (SHA a3a34318429e2bfe99420c65d6b77f5095618064). 
You need to enable routing trace. 
```
NativeScriptRouterModule.forRoot(appRoutes, {enableTracing: true}). 
```
This will lead to core.umd.js:3491:32: EXCEPTION: null is not an object (evaluating 'dom_1.logGroup').

nativescript-anular : 1.3.0
"@angular/router": 3.3.1

**Comment by NickIliev** [comment]
Reproduced with Android

error log:
```
JS:     at Subscriber._next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/Subscriber.js:125:26)
JS:     at Subscriber.next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/Subscriber.js:89:18)
JS:     at Subject.next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/Subject.js:55:25)
JS:     at Router.executeScheduledNavigation (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/router/bundles/router.umd.js:3620:33)
JS:     at MergeMapSubscriber.project (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/router/bundles/router.umd.js:3580:25)
JS:     at MergeMapSubscriber._tryNext (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/operator/mergeMap.js:111:27)
JS:     at MergeMapSubscriber._next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/operator/mergeMap.js:101:18)
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: Cannot read property 'logGroup' of null
JS:
JS: TypeError: Cannot read property 'logGroup' of null
JS:     at SafeSubscriber._next (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/router/bundles/router.umd.js:5355:20)
JS:     at SafeSubscriber.__tryOrUnsub (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/Subscriber.js:223:16)
JS:     at SafeSubscriber.next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/Subscriber.js:172:22)
JS:     at Subscriber._next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/Subscriber.js:125:26)
JS:     at Subscriber.next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/Subscriber.js:89:18)
JS:     at Subject.next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/Subject.js:55:25)
JS:     at Router.executeScheduledNavigation (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/router/bundles/router.umd.js:3620:33)
JS:     at MergeMapSubscriber.project (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/router/bundles/router.umd.js:3580:25)
JS:     at MergeMapSubscriber._tryNext (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/operator/mergeMap.js:111:27)
JS:     at MergeMapSubscriber._next (/data/data/org.nativescript.groceries/files/app/tns_modules/rxjs/operator/mergeMap.js:101:18)

```

**Comment by hdeshev** [comment]
Fixed in master (#660)

**Comment by hdrdiab** [comment]
Is it normal for this error to appear only when running a bundled version of the app?

**Comment by elena-p** [comment]
the fix is in both release and master branches
