### ISSUE TITLE
Returned Promise of platformNativeScriptDynamic().bootstrapModule() is null

### ISSUE THREAD

**Issue by maxfriedmann** [NativeScript/nativescript-angular#763]
### Tell us about the problem
In our project we need a reference to the bootstrapped Angular Application. In SPAs we use the standard `platformBrowserDynamic().bootstrapModule().then` promise which works fine. Unfortunately, the platformNativeScriptDynamic call returns `null`

### Which platform(s) does your issue occur on?
iOS/Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.4
- Cross-platform modules: 2.5.2
- Runtime(s): tns-android 2.5.0 and tns-ios 2.5.0
- Plugin(s): none

### Please tell us how to recreate the issue in as much detail as possible.
This is a fork of the current nativescript hello world template that includes the non-working promise usage: https://github.com/smallstack/template-hello-world-ng
If you start the app you will get : 
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

TypeError: Cannot read property 'then' of null
File: "file:///data/data/org.nativescript.HelloWorld/files/app/main.js, line: 4, column: 80

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.HelloWorld/files/app/main.js', line: 4, column: 81
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'then' of null
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.HelloWorld/files/app/main.js', line: 4, column: 81
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

TypeError: Cannot read property 'then' of null
File: "file:///data/data/org.nativescript.HelloWorld/files/app/main.js, line: 4, column: 80

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.HelloWorld/files/app/main.js', line: 4, column: 81
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'then' of null
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.HelloWorld/files/app/main.js', line: 4, column: 81
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:580)
	at com.tns.Runtime.run(Runtime.java:574)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
	... 8 more
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
This is the code I changed in the nativescript hello world example: https://github.com/NativeScript/template-hello-world-ng/compare/release...smallstack:release

**Comment by m-abs** [comment]
I noticed the same, see explanation here:
https://github.com/NativeScript/nativescript-angular/issues/635

**Comment by maxfriedmann** [comment]
Thanks a lot for linking!
