### ISSUE TITLE
Webpack + LazyLoad Failing

### ISSUE THREAD

**Issue by Niko87** [NativeScript/nativescript-angular#907]
Hi im facing this error when i try to webpack the app.. 

`JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: EXCEPTION: Uncaught (in promise): Error: Cannot find module './login/login.module.ngfactory'.
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): Error: Cannot find module './login/login.module.ngfactory'.
JS:     at resolvePromise (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:55890:31)
JS:     at resolvePromise (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:55875:17)
JS:     at file:///data/data/com.demoapp.demoapp/files/app/vendor.js:55923:17
JS:     at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:55697:37)
JS:     at Object.onInvokeTask (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:18429:37)
JS:     at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:55696:42)
JS:     at Zone.module.exports.Zone.runTask (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:55597:47)
JS:     at drainMicroTaskQueue (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:55829:35)
JS: Unhandled Promise rejection: Cannot find module './login/login.module.ngfactory'. ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot find module './login/login.module.ngfactory'. Error: Cannot find module './login/login.module.ngfactory'.
JS:     at webpackEmptyContext (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:72801:8)
JS:     at NSModuleFactoryLoader.module.exports.NSModuleFactoryLoader.loadFactory (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:54821:49)
JS:     at NSModuleFactoryLoader.module.exports.NSModuleFactoryLoader.load (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:54812:25)
JS:     at RouterConfigLoader.module.exports.RouterConfigLoader.loadModuleFactory (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:15574:128)
JS:     at RouterConfigLoader.module.exports.RouterConfigLoader.load (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:15561:81)
JS:     at MergeMapSubscriber.project (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:70666:111)
JS:     at MergeMapSubscriber.module.exports.MergeMapSubscriber._tryNext (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:18730:27)
JS:     at MergeMapSubscriber.module.exports.MergeMapSubscriber._next (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:18720:18)
JS:     at MergeMapSubscriber.module.exports.Subscriber.next (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:7569:18)
JS:     at ScalarObservable.module.exports.ScalarObservable._subscribe (file:///data/data/com.demoapp.demoapp/files/app/vendor.js:44260:24)
JS: Error: Uncaught (in promise): Error: Cannot find module './login/login.module.ngfactory'.`

my packaje.json is:

````
{
  "description": "App",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.demoapp.demoapp",
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "nativescript-angular": "1.4.0",
    "nativescript-angular-snapshot": "1.4.0-5.5.372.32-1",
    "nativescript-fresco": "^1.0.16",
    "nativescript-ngx-fonticon": "^2.2.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "^3.10.2",
    "nativescript-social-share": "^1.3.2",
    "nativescript-telerik-ui": "^1.6.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-videoplayer": "^2.4.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.1",
    "tns-platform-declarations": "^2.5.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.4.3",
    "@ngtools/webpack": "1.2.13",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "nativescript-dev-webpack": "^0.6.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "typescript": "~2.1.6",
    "webpack": "~2.5.1",
    "webpack-sources": "~0.2.3",
    "zone.js": "~0.7.2"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
`

app.routing.ts

`export const routes = [
    { path: "", redirectTo: "login" , pathMatch: "full"},
    { path: "login", loadChildren: "./login/login.module#LoginModule" },
];
```
`
app.module.ts

`@NgModule({
  imports: [
    NativeScriptModule,
    NativeScriptRouterModule,
    NativeScriptRouterModule.forRoot(routes),
  ],
  declarations: [
    AppComponent,
  ],
  bootstrap: [AppComponent],
  providers: [{provide: NgModuleFactoryLoader, useClass: NSModuleFactoryLoader }],
  schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule { }
`

the app runs well without webpacking...

**Comment by Niko87** [comment]
i upgrade the whole packages... another problems now ... closing..
