### ISSUE TITLE
ngModel on Switch Throws Exception

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-angular#908]
The following exception is thrown on Android when a switch has `[(ngModel)]` applied. Normal behavior is observed on iOS with the same view settings.

``` xml
 <Switch row="0" col="1" [(ngModel)]="event.isPrivate" class="switch right"></Switch>
```

### tns-info:
```
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 3.1.1           │ 3.1.2          │ Update available │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date       │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date       │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date       │
```
### deps
``` js
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/router": "~4.1.0",
    "email-validator": "1.0.7",
    "nativescript-angular": "~3.1.1",
    "nativescript-camera": "^3.0.1",
    "nativescript-custom-entitlements": "^0.2.0",
    "nativescript-dom": "^2.0.0",
    "nativescript-drop-down": "^3.1.0",
    "nativescript-feedback": "^1.0.5",
    "nativescript-floatingactionbutton": "^3.0.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-google-maps-sdk": "^2.3.2",
    "nativescript-imagepicker": "^3.0.2",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-ngx-fonticon": "^2.2.1",
    "nativescript-plugin-firebase": "^4.0.3",
    "nativescript-telerik-ui-pro": "file:./NativeScriptUIPro/nativescript-ui-pro.tgz",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toasty": "^1.1.5",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.2",
    "@ngtools/webpack": "1.3.1",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "husky": "^0.13.4",
    "lazy": "1.0.11",
    "lint-staged": "^4.0.0",
    "nativescript-css-loader": "~0.26.1",
    "nativescript-dev-sass": "^1.2.0",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "^0.6.3",
    "prettier": "^1.4.4",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "tslint": "5.5.0",
    "typescript": "~2.3.2",
    "webpack": "~2.5.1",
    "webpack-sources": "~0.2.3"
  },
```

```
JS: Error: Failed to apply property [background-color] with value [#eee] to Switch(328). TypeError: value1.equals is not a function
JS: Error: Failed to apply property [background-color] with value [#eee] to Switch(328). TypeError: value1.equals is not a function
JS: Error: Failed to apply property [background-color] with value [#eee] to Switch(328). TypeError: value1.equals is not a function
JS: ERROR Error: Uncaught (in promise): Error: java.lang.Exception: Failed resolving method setChecked on class android.widget.Switch
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:1004)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:912)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:896)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:888)
JS:     com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__TouchListenerImpl.onTouch(Object_frnal_ts_helpers_l58_c38__TouchListenerImpl.java:13)
JS:     android.view.View.dispatchTouchEvent(View.java:11524)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2925)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2606)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:423)
JS:     com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1821)
JS:     android.app.Activity.dispatchTouchEvent(Activity.java:3291)
JS:     com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:385)
JS:     android.view.View.dispatchPointerEvent(View.java:11767)
JS:     android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4765)
JS:     android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4579)
JS:     android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4117)
JS:     android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4170)
JS:     android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4136)
JS:     android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4263)
JS:     android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4144)
JS:     android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4320)
JS:     android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4117)
JS:     android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4170)
JS:     android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4136)
JS:     android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4144)
JS:     android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4117)
JS:     android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6631)
JS:     android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6605)
JS:     android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6566)
JS:     android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootI
JS: mpl.java:6734)
JS:     android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
JS:     android.os.MessageQueue.nativePollOnce(Native Method)
JS:     android.os.MessageQueue.next(MessageQueue.java:325)
JS:     android.os.Looper.loop(Looper.java:142)
JS:     android.app.ActivityThread.main(ActivityThread.java:6540)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
JS: Error: java.lang.Exception: Failed resolving method setChecked on class android.widget.Switch
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:1004)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:912)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:896)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:888)
JS:     com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__TouchListenerImpl.onTouch(Object_frnal_ts_helpers_l58_c38__TouchListenerImpl.java:13)
JS:     android.view.View.dispatchTouchEvent(View.java:11524)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2925)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2606)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2931)
JS:     android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2620)
JS:     com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:423)
JS:     com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1821)
JS:     android.app.Activity.dispatchTouchEvent(Activity.java:3291)
JS:     com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:385)
JS:     android.view.View.dispatchPointerEvent(View.java:11767)
JS:     android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4765)
JS:     android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4579)
JS:     android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4117)
JS:     android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4170)
JS:     android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4136)
JS:     android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4263)
JS:     android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4144)
JS:     android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4320)
JS:     android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4117)
JS:     android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4170)
JS:     android.view.ViewRootImpl$InputSta
JS: ge.forward(ViewRootImpl.java:4136)
JS:     android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4144)
JS:     android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4117)
JS:     android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6631)
JS:     android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6605)
JS:     android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6566)
JS:     android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6734)
JS:     android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
JS:     android.os.MessageQueue.nativePollOnce(Native Method)
JS:     android.os.MessageQueue.next(MessageQueue.java:325)
JS:     android.os.Looper.loop(Looper.java:142)
JS:     android.app.ActivityThread.main(ActivityThread.java:6540)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
JS:     at Switch.(anonymous function) (file:///data/data/com.picpin/files/app/tns_modules/tns-core-modules/ui/switch/switch.js:57:25)
JS:     at Switch.Property.set [as checked] (file:///data/data/com.picpin/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js:103:44)
JS:     at CheckedValueAccessor.writeValue (file:///data/data/com.picpin/files/app/tns_modules/nativescript-angular/value-accessors/checked-value-accessor.js:25:27)
JS:     at setUpControl (file:///data/data/com.picpin/files/app/tns_modules/@angular/forms/bundles/forms.umd.js:1749:27)
JS:     at NgModel._setUpStandalone (file:///data/data/com.picpin/files/app/tns_modules/@angular/forms/bundles/forms.umd.js:4311:9)
JS:     at NgModel._setUpControl (file:///data/data/com.picpin/files/app/tns_modules/@angular/forms/bundles/forms.umd.js:4297:37)
JS:     at NgModel.ngOnChanges (file:///data/data/com.picpin/files/app/tns_modules/@angular/forms/bundles/forms.umd.js:4228:18)
JS:     at checkAndUpdateDirectiveInline (file:///data/data/com.picpin/files/app/tns_modules/@angular/core/bundles/core.umd.js:10819:19)
JS:     at checkAndUpdateNodeInline (file:///data/data/com.picpin/files/app/tns_modules/@angular/core/bundles/core.umd.js:12245:17)
JS:     at checkAndUpdateNode (file:///data/data/com.picpin/files/app/tns_modules/@angular/core/bundles/core.umd.js:12184:16)
JS:     at debugCheckAndUpdateNode (file:///data/data/com.picpin/files/app/tns_modules/@angular/core/bundles/core.umd.js:12887:59)
JS:     at debugCheckDirectivesFn (file:///data/data/com.picpin/files/app/tns_modules/@angular/core/bundles/core.umd.js:12828:13)
JS:     at Object.View_CreateEventComponent_0.co [as updateDirectives] (ng:///CreateEventModule/CreateEventComponent.ngfactory.js:1415:5)
JS:     at Object.debugUpdateDirectives [as updateDirectives] (file:///data/data/com.picpin/files/app/tns_modules/@angular/core/bundles/core.umd.js:12813:21)
JS:     at checkAndUpdateView (file:///data/data/com.picpin/files/app/tns_modules/@angular/core/bundles/core.umd.js:12151:14)
```

**Comment by tsonevn** [comment]
Hi @bradmartin,
 I tested this case on my side with nativescript-angular 3.1.3 and the project will not crash while using ngModel for the Switch component, however, the ngModel will not work properly and the value, which is setup from code behind will not be changed properly. Could you verify this case on your side?

**Comment by justintoth** [comment]
This is still an issue...

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.lang.Exception: Failed resolving method setChecked on class android.widget.Switch
System.err: 
System.err: StackTrace:
System.err: [checked:setNative](file: node_modules/@nativescript/core/ui/switch/index.android.js:67:0)
System.err:     at applyAllNativeSetters(file: node_modules/@nativescript/core/ui/core/properties/index.js:1137:0)
System.err:     at initNativeView(file: node_modules/@nativescript/core/ui/core/properties/index.js:1080:0)
System.err:     at onResumeNativeUpdates(file: node_modules/@nativescript/core/ui/core/view-base/index.js:737:22)
System.err:     at _resumeNativeUpdates(file: node_modules/@nativescript/core/ui/core/view-base/index.js:280:0)

```

**Comment by edusperoni** [comment]
@justintoth the error might be the same but the conditions can be different. Please share more details about how you're using it.
